modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
# issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
# updateJSONURL="https://change.me.example.invalid/updates.json"
# displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile = "turtleblockacademylogo.png" #optional
#credits="" #optional
authors = "${mod_authors}"
displayTest = "MATCH_VERSION"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "curios"
mandatory = true
versionRange = "[1.19.2-5.1.6.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "sereneseasons"
mandatory = true
versionRange = "[1.19.2-8.1.0.24,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "cagerium"
mandatory = true
versionRange = "[1.19.2-1.1.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "resourcefullib"
mandatory = true
versionRange = "[1.1.24,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "lootbags"
mandatory = true
versionRange = "[1.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "dimdungeons"
mandatory = true
versionRange = "[179,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "terrablender"
mandatory = true
versionRange = "[2.0.1.166,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "biomesoplenty"
mandatory = true
versionRange = "[17.1.2.544,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "ecologics"
mandatory = true
versionRange = "[2.1.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "unusualend"
mandatory = true
versionRange = "[1.4.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "phantasm"
mandatory = true
versionRange = "[1.2.10.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "aether"
mandatory = true
versionRange = "[1.19.2-1.4.0-forge,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "mining_dimension"
mandatory = true
versionRange = "[1.19.2-1.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.19.2-1.2.3,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "farmersrespite"
mandatory = true
versionRange = "[1.19-2.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "delightful"
mandatory = false
versionRange = "[3.3,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "festive_delight"
mandatory = true
versionRange = "[1.3.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "fastfooddelight"
mandatory = true
versionRange = "[1.19-1.2.3,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "chefsdelight"
mandatory = true
versionRange = "[1.0.2-forge-1.19.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "oceansdelight"
mandatory = true
versionRange = "[1.0.2-1.19.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "ends_delight"
mandatory = true
versionRange = "[1.19.2-1.2.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "nethersdelight"
mandatory = true
versionRange = "[1.19-3.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "crabbersdelight"
mandatory = true
versionRange = "[1.1.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "decoration_delight"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "cratedelight"
mandatory = true
versionRange = "[1.0.5-1.19.2-forge,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "storagedelight"
mandatory = true
versionRange = "[1.0.2-1.19.2-forge,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.1.40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "kawaiidishes"
mandatory = true
versionRange = "[1.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "drinkbeer"
mandatory = true
versionRange = "[1.0.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "salt"
mandatory = true
versionRange = "[1.2.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "wares"
mandatory = true
versionRange = "[1.2.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "sophisticatedcore"
mandatory = true
versionRange = "[1.19.2-0.6.4.587,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "sophisticatedbackpacks"
mandatory = true
versionRange = "[1.19.2-3.20.2.1035,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "refinedstorage"
mandatory = true
versionRange = "[1.11.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "moonlight"
mandatory = true
versionRange = "[1.19.2-2.2.46,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "supplementaries"
mandatory = true
versionRange = "[1.19.2-2.3.23,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "advancementframes"
mandatory = true
versionRange = "[1.19.2-2.0.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "hauntedharvest"
mandatory = true
versionRange = "[1.19.2-3.1.6,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "snowyspirit"
mandatory = true
versionRange = "[1.19.2-2.1.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "moa_decor_toys"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "moa_decor_bath"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "moa_decor_holidays"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "moa_decor_art"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "moa_decor_cookery"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "moa_decor_garden_"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "plushies"
mandatory = true
versionRange = "[1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "mcwlights"
mandatory = true
versionRange = "[1.0.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "mcwpaths"
mandatory = true
versionRange = "[1.0.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "additional_lights"
mandatory = true
versionRange = "[2.1.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "justoutdoorstuffs"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "chimes"
mandatory = true
versionRange = "[2.0.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "friendsandfoes"
mandatory = true
versionRange = "[2.0.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "guardvillagers"
mandatory = true
versionRange = "[1.19.2-1.5.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "beautify"
mandatory = true
versionRange = "[1.4.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "mantle"
mandatory = true
versionRange = "[1.10.24,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "tconstruct"
mandatory = true
versionRange = "[3.8.1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "mcwdoors"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "mcwtrpdoors"
mandatory = true
versionRange = "[1.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "artifacts"
mandatory = true
versionRange = "[1.19.2-5.0.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "patchouli"
mandatory = true
versionRange = "[1.19.2-77,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "villagersplus"
mandatory = true
versionRange = "[1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "bookshelf"
mandatory = true
versionRange = "[16.3.20,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "gamestages"
mandatory = true
versionRange = "[11.1.5,)"
ordering = "NONE"
side = "BOTH"