#@formatter:off
modLoader = "javafml"
loaderVersion = "[43,)"
license = "GNU_GPL.3"
# issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId = "turtleblockacademy"
version = "${file.jarVersion}"
displayName = "Turtle Block Academy"
# updateJSONURL="https://change.me.example.invalid/updates.json"
# displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile = "logo.png"
credits = '''Special thanks to my sons, my parents, and my supporters: Marshal Nash, for supporting my blog and my various projects!'''
authors = "Warren Tode (ToadieOdie)"
displayTest = "MATCH_VERSION"
description = '''Just a compat mod I've put together to use for homeschooling, but can be used for roleplay as well.
An additional location to report issues or ask questions is on my discord at: https://discord.gg/gB8PjQgZ4Q
'''

[[dependencies.turtleblockacademy]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "curios"
mandatory = true
versionRange = "[1.19.2-5.1.6.1,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "sereneseasons"
mandatory = true
versionRange = "[1.19.2-8.1.0.24,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "todecoins"
mandatory = false
versionRange = "[1.19.2-2.1.2.6.beta,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "cagerium"
mandatory = false
versionRange = "[1.19.2-1.1.8,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "resourcefullib"
mandatory = true
versionRange = "[1.1.24,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "lootbags"
mandatory = true
versionRange = "[1.1.2,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "dimdungeons"
mandatory = true
versionRange = "[179,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "terrablender"
mandatory = true
versionRange = "[2.0.1.166,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "biomesoplenty"
mandatory = true
versionRange = "[17.1.2.544,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "ecologics"
mandatory = true
versionRange = "[2.1.11,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "unusualend"
mandatory = true
versionRange = "[1.4.3,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "phantasm"
mandatory = true
versionRange = "[1.2.10.5,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "aether"
mandatory = true
versionRange = "[1.19.2-1.4.2-forge,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.19.2-1.2.3,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "farmersrespite"
mandatory = true
versionRange = "[1.19-2.0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "delightful"
mandatory = true
versionRange = "[3.3,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "festive_delight"
mandatory = true
versionRange = "[1.3.0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "fastfooddelight"
mandatory = true
versionRange = "[1.19-1.2.3,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "chefsdelight"
mandatory = true
versionRange = "[1.0.2-forge-1.19.2,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "oceansdelight"
mandatory = true
versionRange = "[1.0.2-1.19.2,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "ends_delight"
mandatory = true
versionRange = "[1.19.2-1.2.1,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "nethersdelight"
mandatory = true
versionRange = "[1.19-3.0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "crabbersdelight"
mandatory = true
versionRange = "[1.1.2,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "decoration_delight"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "cratedelight"
mandatory = true
versionRange = "[1.0.5-1.19.2-forge,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "storagedelight"
mandatory = true
versionRange = "[1.0.2-1.19.2-forge,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "miners_delight"
mandatory = false
versionRange = "[1.19.2-1.1.2,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.1.40,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "kawaiidishes"
mandatory = true
versionRange = "[1.10,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "drinkbeer"
mandatory = true
versionRange = "[1.0.3,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "salt"
mandatory = true
versionRange = "[1.2.4,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "wares"
mandatory = false
versionRange = "[1.2.8,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "sophisticatedcore"
mandatory = true
versionRange = "[1.19.2-0.6.4.587,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "sophisticatedbackpacks"
mandatory = true
versionRange = "[1.19.2-3.20.2.1035,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "refinedstorage"
mandatory = true
versionRange = "[1.11.7,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "moonlight"
mandatory = true
versionRange = "[1.19.2-2.2.46,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "supplementaries"
mandatory = true
versionRange = "[1.19.2-2.3.23,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "advancementframes"
mandatory = false
versionRange = "[1.19.2-2.0.0,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "hauntedharvest"
mandatory = true
versionRange = "[1.19.2-3.1.6,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "snowyspirit"
mandatory = true
versionRange = "[1.19.2-2.1.10,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "moa_decor_toys"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "moa_decor_bath"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "moa_decor_holidays"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "moa_decor_art"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "moa_decor_cookery"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "moa_decor_garden_"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "plushies"
mandatory = true
versionRange = "[1.2,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "mcwlights"
mandatory = false
versionRange = "[1.0.6,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "additional_lights"
mandatory = true
versionRange = "[2.1.6,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "justoutdoorstuffs"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "chimes"
mandatory = true
versionRange = "[2.0.1,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "friendsandfoes"
mandatory = true
versionRange = "[2.0.10,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "guardvillagers"
mandatory = false
versionRange = "[1.19.2-1.5.7,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "beautify"
mandatory = true
versionRange = "[1.4.3,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "mantle"
mandatory = true
versionRange = "[1.10.24,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.turtleblockacademy]]
modId = "tconstruct"
mandatory = true
versionRange = "[3.8.1.16,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "mcwdoors"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "mcwtrpdoors"
mandatory = true
versionRange = "[1.1.1,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "artifacts"
mandatory = true
versionRange = "[1.19.2-5.0.5,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "patchouli"
mandatory = true
versionRange = "[1.19.2-77,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.turtleblockacademy]]
modId = "villagersplus"
mandatory = true
versionRange = "[1.2,)"
ordering = "BEFORE"
side = "BOTH"