
["Toolsmith Trade Settings"]

	["Toolsmith Trade Settings"."Toolsmith Level One Trade One"]
		# Toolsmith 1 Trade Request 1 Table
		toolsmith_1_trade_request_1_table = "todecoins:trade_tables/misc/one_emerald_value_fuel_table"
		# Toolsmith 1 Trade Offer 1 Table
		toolsmith_1_trade_offer_1_table = "todecoins:trade_tables/currency/single_emerald_value_currency"

	["Toolsmith Trade Settings"."Toolsmith Level One Trade Two"]
		# Toolsmith 1 Trade Request 2 Table
		toolsmith_1_trade_request_2_table = "todecoins:trade_tables/currency/single_emerald_value_currency"
		# Toolsmith 1 Trade Offer 2 Table
		toolsmith_1_trade_offer_2_table = "todecoins:trade_tables/tools/stone_tier_tools"

	["Toolsmith Trade Settings"."Toolsmith Level Two Trade One"]
		# Toolsmith 2 Trade Request 1 Table
		toolsmith_2_trade_request_1_table = "todecoins:trade_tables/metals/single_emerald_value_metals"
		# Toolsmith 2 Trade Offer 1 Table
		toolsmith_2_trade_offer_1_table = "todecoins:trade_tables/currency/single_emerald_value_currency"

	["Toolsmith Trade Settings"."Toolsmith Level Two Trade Two"]
		# Rare Trade
		# Toolsmith 2 Trade Request 2 Table
		toolsmith_2_trade_request_2_table = "todecoins:trade_tables/currency/thirty_six_emerald_value_currency"
		# Toolsmith 2 Trade Offer 2 Table
		toolsmith_2_trade_offer_2_table = "todecoins:trade_tables/misc/bell_table"

	["Toolsmith Trade Settings"."Toolsmith Level Three Trade One"]
		# Toolsmith 3 Trade Request 1 Table
		toolsmith_3_trade_request_1_table = "todecoins:trade_tables/tools/iron_tier_tools"
		# Toolsmith 3 Trade Offer 1 Table
		toolsmith_3_trade_offer_1_table = "todecoins:trade_tables/currency/three_emerald_value_currency"

	["Toolsmith Trade Settings"."Toolsmith Level Three Trade Two"]
		# Toolsmith 3 Trade Request 2 Table
		toolsmith_3_trade_request_2_table = "todecoins:trade_tables/misc/flint_buy_table"
		# Toolsmith 3 Trade Offer 2 Table
		toolsmith_3_trade_offer_2_table = "todecoins:trade_tables/currency/single_emerald_value_currency"

	["Toolsmith Trade Settings"."Toolsmith Level Four Trade One"]
		# Rare Trade
		# Toolsmith 4 Trade Request 1 Table
		toolsmith_4_trade_request_1_table = "todecoins:trade_tables/currency/emerald_quarter_bank_note_value_currency"
		# Toolsmith 4 Trade Offer 1 Table
		toolsmith_4_trade_offer_1_table = "todecoins:trade_tables/tools/iron_tier_tools"

	["Toolsmith Trade Settings"."Toolsmith Level Four Trade Two"]
		# Toolsmith 4 Trade Request 2 Table
		toolsmith_4_trade_request_2_table = "todecoins:trade_tables/currency/four_emerald_value_currency"
		# Toolsmith 4 Trade Offer 2 Table
		toolsmith_4_trade_offer_2_table = "todecoins:trade_tables/tools/diamond_tier_tools"

	["Toolsmith Trade Settings"."Toolsmith Level Four Trade Three"]
		# Available if Supplementaries is Loaded
		# Toolsmith 4 Trade Request 3 Table
		toolsmith_4_trade_request_3_table = "todecoins:trade_tables/currency/single_emerald_value_currency"
		# Toolsmith 4 Trade Offer 3 Table
		toolsmith_4_trade_offer_3_table = "todecoins:trade_tables/misc/tagged_ash_table"
		toolsmith_4_trade_offer_2_count = 18

	["Toolsmith Trade Settings"."Toolsmith Level Five Trade One"]
		# Rare Trade
		# Toolsmith 5 Trade Request 1 Table
		toolsmith_5_trade_request_1_table = "todecoins:trade_tables/currency/twenty_emerald_value_currency"
		# Toolsmith 5 Trade Offer 1 Table
		toolsmith_5_trade_offer_1_table = "todecoins:trade_tables/tools/gold_tier_tools"

	["Toolsmith Trade Settings"."Toolsmith Level Five Trade Two"]
		# Rare Trade
		# Toolsmith 5 Trade Request 2 Table
		toolsmith_5_trade_request_2_table = "todecoins:trade_tables/currency/single_lucky_coin_bag_value_currency"
		# Toolsmith 5 Trade Offer 2 Table
		toolsmith_5_trade_offer_2_table = "todecoins:trade_tables/tools/netherite_tier_tools"

	["Toolsmith Trade Settings"."Toolsmith Level Five Trade Three"]
		# Rare Trade
		# Toolsmith 5 Trade Request 3 Table
		toolsmith_5_trade_request_3_table = "todecoins:trade_tables/currency/twenty_six_emerald_value_currency"
		# Toolsmith 5 Trade Offer 3 Table
		toolsmith_5_trade_offer_3_table = "todecoins:trade_tables/tools/diamond_tier_tools"

