
[time_settings]
	#The duration of a Minecraft day in ticks.
	#This only adjusts the internal length of a day used by the season cycle.
	#It is intended to be used in conjunction with another mod which adjusts the actual length of a Minecraft day.
	#Range: > 20
	day_duration = 24000
	#The duration of a sub season in days
	#Range: > 1
	sub_season_duration = 30
	#The starting sub season for new worlds.
	#0 = Random, 1 - 3 = Early/Mid/Late Spring
	#4 - 6 = Early/Mid/Late Summer
	#7 - 9 = Early/Mid/Late Autumn
	#10 - 12 = Early/Mid/Late Winter
	#Range: 0 ~ 12
	starting_sub_season = 1
	#If the season should progress on a server with no players online
	progress_season_while_offline = true

[aesthetic_settings]
	#Change the grass color based on the current season
	change_grass_color = true
	#Change the foliage colour based on the current season
	change_foliage_color = true
	#Change the birch colour based on the current season
	change_birch_color = true

[dimension_settings]
	#Seasons will only apply to dimensons listed here
	whitelisted_dimensions = ["minecraft:overworld", "minecraft:nether", "minecraft:end", "dimdungeons:dungeon_dimension", "dimdungeons:build_dimension", "nomadictents:tent", "aether:the_aether"]

[biome_settings]
	#Biomes in which seasons will not apply.
	blacklisted_biomes = ["minecraft:lush_caves", "minecraft:dripstone_caves", "minecraft:ocean", "minecraft:deep_ocean", "minecraft:frozen_ocean", "minecraft:deep_frozen_ocean", "minecraft:cold_ocean", "minecraft:deep_cold_ocean", "minecraft:lukewarm_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:warm_ocean", "minecraft:river", "minecraft:the_void", "biomesoplenty:glowing_grotto", "biomesoplenty:spider_nest", "minecraft:the_end", "minecraft:small_end_islands", "minecraft:end_midlands", "minecraft:end_highlands", "minecraft:end_barrens", "aether:sky_root_forest", "aether:sky_root_grove", "aether:sky_root_meadow", "aether:sky_root_woodland", "nomadictents:tent", "dimdungeons:biome_dungeon"]
	#Biomes which use tropical seasons.
	tropical_biomes = ["minecraft:mangrove_swamp", "minecraft:swamp", "minecraft:warm_ocean", "biomesoplenty:withered_abyss", "biomesoplenty:visceral_heap", "biomesoplenty:undergrowth", "biomesoplenty:erupting_inferno", "biomesoplenty:crystalline_chasm", "minecraft:nether_wastes", "minecraft:soul_valley", "minecraft:crimson_forest", "minecraft:warped_forest", "minecraft:basalt_deltas"]