
# Let's Configure Delightful
[Knives]
	adamantium_knife = false
	allthemodium_knife = false
	amethyst_knife = true
	black_opal_knife = false
	bone_knife = true
	brass_knife = false
	bronze_knife = false
	constantan_knife = false
	copper_knife = true
	deorum_knife = false
	draco_arcanus_knife = false
	electrum_knife = false
	emerald_knife = true
	enderite_knife = false
	experience_knife = false
	fiery_knife = false
	gilded_quartz_knife = false
	invar_knife = false
	ironwood_knife = false
	kiwano_knife = false
	knightmetal_knife = false
	lapis_lazuli_knife = true
	large_amethyst_knife = false
	lead_knife = false
	leaf_knife = false
	living_knife = false
	mythril_knife = false
	netherite_opal_knife = false
	nickel_knife = false
	obsidian_infused_enderite_knife = false
	onyx_knife = false
	osmium_knife = false
	pendorite_knife = false
	refined_glowstone_knife = false
	refined_obsidian_knife = false
	reinforced_deorum_knife = false
	silver_knife = false
	sinisite_knife = false
	steel_knife = false
	steeleaf_knife = false
	thyrium_knife = false
	tin_knife = false
	warden_knife = false
	zinc_knife = false
	adamantite_knife = true
	blazing_knife = true
	crystalline_knife = true
	stellium_knife = true
	alf_knife = true
	cloggrum_knife = true
	elementium_knife = true
	forgotten_knife = true
	froststeel_knife = true
	gilded_netherite_knife = true
	manasteel_knife = true
	necronium_knife = true
	rose_gold_knife = true
	soul_steel_knife = true
	terra_knife = true
	utherium_knife = true

[Generation]
	#Chance of generating clusters. Smaller value = more frequent (once every ...). To disable, set the item Salmonberries to false above.
	#Range: > 0
	chance_wild_salmonberries = 30
	#Chance of generating clusters. Smaller value = more frequent (once every ...). To disable, set the item Mini Melon to false above.
	#Range: > 0
	chance_mini_melon = 30
	#Chance of generating clusters. Smaller value = more frequent (once every ...). To disable, set the item Cantaloupe to false above.
	#Range: > 0
	chance_cantaloupe = 30

["Registry & Recipes"]
	acorn = true
	acorn_sack = true
	animal_fat = true
	animal_oil_bottle = true
	azalea_tea = true
	basalt_cabinet = true
	berry_matcha_latte = true
	cactus_flesh = true
	cactus_steak = true
	cantaloupe = true
	cantaloupe_slice = true
	cheeseburger = true
	chopped_clover = true
	chunk_nugget = true
	chunkwich = true
	coconut_curry = true
	cooked_goat = true
	cooked_marshmallow_stick = true
	cooked_venison_chops = true
	crab_rangoon = true
	deluxe_cheeseburger = true
	ender_nectar = true
	field_salad = true
	glow_jelly_bottle = true
	green_tea_leaf = false
	honey_glazed_walnut = true
	jelly_bottle = true
	lavender_tea = true
	marshmallow_stick = true
	matcha = true
	matcha_ice_cream = true
	matcha_ice_cream_block = true
	matcha_latte = true
	mini_melon = true
	nut_butter_and_jelly_sandwich = true
	nut_butter_bottle = true
	prickly_pear_juice = true
	quartz_cabinet = true
	raw_goat = true
	rock_candy = true
	salmonberries = true
	salmonberry_gummy = true
	salmonberry_ice_cream = true
	salmonberry_ice_cream_block = true
	salmonberry_pie = true
	salmonberry_pips = true
	salmonberry_sack = true
	sinigang = true
	smore = true
	venison_chops = true
	wild_salmonberries = true
	#Force the replacement of forge:cheese item tag in recipes with forge:milk
	use_milk_tag = true
	#Allow cooking milk from nuts
	nut_milk = true
	#Allow cooking honey from honey and clovers
	clover_honey = true
	#Give items that are sliced off of blocks directly to player's inventory instead of dropping
	give_sliced_directly = true
	#Allow sliced melons to be juiced in-world (right click)
	melon_juicing = true
	baobab_fruit_crate = false
	blueberry_sack = false
	crimson_berry_sack = false
	green_apple_crate = false
	joshua_fruit_crate = false
	nightshade_berry_sack = false

["Pie Overhauls"]
	blueberry_pie_slice = false
	crimson_berry_pie_slice = false
	gloomgourd_pie_slice = false
	green_apple_pie_slice = false
	nightshade_berry_pie_slice = false
	pumpkin_pie_slice = true
	salmonberry_pie_slice = true
	source_berry_pie_slice = false

