package com.github.warrentode.turtleblockacademy.datagen.tags;

import biomesoplenty.api.biome.BOPBiomes;
import com.aetherteam.aether.data.resources.registries.AetherBiomes;
import com.github.warrentode.turtleblockacademy.util.TBATags;
import com.github.warrentode.turtleblockacademy.world.biome.TBABiomes;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.tags.BiomeTagsProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BiomeTags;
import net.minecraft.world.level.biome.Biomes;
import net.minecraftforge.common.Tags;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.Objects;

public class BiomeTagsGen extends BiomeTagsProvider {
    public BiomeTagsGen(DataGenerator generator, String modid, @Nullable ExistingFileHelper helper) {
        super(generator, modid, helper);
    }

    @Override
    protected void addTags() {
        tag(TBATags.Biomes.HAS_ORANGE_AUTUMN)
                .addOptional(BOPBiomes.SEASONAL_FOREST.location())
                .addOptional(BOPBiomes.PUMPKIN_PATCH.location());
        tag(TBATags.Biomes.HAS_YELLOW_AUTUMN)
                .addOptional(BOPBiomes.SEASONAL_FOREST.location())
                .addOptional(BOPBiomes.SEASONAL_ORCHARD.location());
        tag(TBATags.Biomes.HAS_ORIGIN)
                .addOptional(BOPBiomes.ORIGIN_VALLEY.location());
        tag(TBATags.Biomes.HAS_MAPLE)
                .addOptional(BOPBiomes.BOG.location())
                .addOptional(BOPBiomes.MAPLE_WOODS.location())
                .addOptional(BOPBiomes.SEASONAL_FOREST.location())
                .addOptional(BOPBiomes.SNOWY_MAPLE_WOODS.location())
                .addOptional(BOPBiomes.TUNDRA.location());
        tag(TBATags.Biomes.HAS_RAINBOW_BIRCH)
                .addOptional(BOPBiomes.AURORAL_GARDEN.location());
        tag(TBATags.Biomes.HAS_FLOWERING_OAK)
                .addOptional(BOPBiomes.LAVENDER_FIELD.location())
                .addOptional(BOPBiomes.LAVENDER_FOREST.location())
                .addOptional(BOPBiomes.MEDITERRANEAN_FOREST.location())
                .addOptional(BOPBiomes.MYSTIC_GROVE.location())
                .addOptional(BOPBiomes.ORCHARD.location())
                .addOptional(BOPBiomes.TROPICS.location())
                .addOptional(BOPBiomes.BAMBOO_GROVE.location())
                .addOptional(BOPBiomes.CHERRY_BLOSSOM_GROVE.location());
        tag(TBATags.Biomes.HAS_BURNING_BLOSSOM)
                .addOptional(BOPBiomes.UNDERGROWTH.location());
        tag(TBATags.Biomes.HAS_ICY_IRIS)
                .addOptional(BOPBiomes.AURORAL_GARDEN.location());
        tag(TBATags.Biomes.HAS_LAVENDER)
                .addOptional(BOPBiomes.LAVENDER_FIELD.location())
                .addOptional(BOPBiomes.LAVENDER_FOREST.location());
        tag(TBATags.Biomes.HAS_PINK_DAFFODIL)
                .addOptional(BOPBiomes.BAMBOO_GROVE.location())
                .addOptional(BOPBiomes.CHERRY_BLOSSOM_GROVE.location())
                .addOptional(BOPBiomes.MYSTIC_GROVE.location());
        tag(TBATags.Biomes.HAS_GLOWFLOWER)
                .addOptional(BOPBiomes.MYSTIC_GROVE.location());
        tag(TBATags.Biomes.HAS_AZURE_BLUET)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.PLAINS)
                .add(Biomes.MEADOW)
                .addOptional(BOPBiomes.CLOVER_PATCH.location())
                .addOptional(BOPBiomes.FIELD.location())
                .addOptional(BOPBiomes.FORESTED_FIELD.location())
                .addOptional(BOPBiomes.MYSTIC_GROVE.location());
        tag(TBATags.Biomes.HAS_WITHER_ROSE)
                .add(Biomes.SOUL_SAND_VALLEY)
                .add(Biomes.BASALT_DELTAS)
                .add(Biomes.CRIMSON_FOREST)
                .add(Biomes.WARPED_FOREST)
                .add(Biomes.NETHER_WASTES)
                .addOptional(BOPBiomes.UNDERGROWTH.location())
                .addOptional(BOPBiomes.WITHERED_ABYSS.location())
                .addOptional(BOPBiomes.OMINOUS_WOODS.location());
        tag(TBATags.Biomes.HAS_ROSE)
                .addOptional(BOPBiomes.ORIGIN_VALLEY.location());
        tag(TBATags.Biomes.HAS_ORANGE_COSMOS)
                .addOptional(BOPBiomes.RAINFOREST.location());
        tag(TBATags.Biomes.HAS_VIOLET)
                .addOptional(BOPBiomes.AURORAL_GARDEN.location())
                .addOptional(BOPBiomes.HIGHLAND_MOOR.location())
                .addOptional(BOPBiomes.SNOWY_CONIFEROUS_FOREST.location())
                .addOptional(BOPBiomes.SNOWY_FIR_CLEARING.location());
        tag(TBATags.Biomes.HAS_PINK_HIBISCUS)
                .addOptional(BOPBiomes.TROPICS.location());
        tag(TBATags.Biomes.HAS_BLUE_HYDRANGEA)
                .addOptional(BOPBiomes.MYSTIC_GROVE.location())
                .addOptional(BOPBiomes.TROPICS.location());
        tag(TBATags.Biomes.HAS_WILTED_LILY)
                .addOptional(BOPBiomes.WOODED_WASTELAND.location());
        tag(TBATags.Biomes.HAS_CATTAIL)
                .addOptional(BOPBiomes.WETLAND.location());
        tag(TBATags.Biomes.HAS_WILDFLOWER)
                .addOptional(BOPBiomes.WOODED_SCRUBLAND.location())
                .addOptional(BOPBiomes.SCRUBLAND.location())
                .addOptional(BOPBiomes.LUSH_DESERT.location());
        tag(TBATags.Biomes.HAS_GOLDENROD)
                .addOptional(BOPBiomes.PRAIRIE.location())
                .addOptional(BOPBiomes.OLD_GROWTH_WOODLAND.location())
                .addOptional(BOPBiomes.WOODLAND.location());
        tag(TBATags.Biomes.HAS_WHITE_FLOWER)
                .addOptional(AetherBiomes.SKYROOT_WOODLAND.location())
                .addOptional(AetherBiomes.SKYROOT_MEADOW.location())
                .addOptional(AetherBiomes.SKYROOT_GROVE.location())
                .addOptional(AetherBiomes.SKYROOT_FOREST.location());
        tag(TBATags.Biomes.HAS_PURPLE_FLOWER)
                .addOptional(AetherBiomes.SKYROOT_WOODLAND.location())
                .addOptional(AetherBiomes.SKYROOT_MEADOW.location())
                .addOptional(AetherBiomes.SKYROOT_GROVE.location())
                .addOptional(AetherBiomes.SKYROOT_FOREST.location());
        tag(TBATags.Biomes.HAS_GREENHEART)
                .add(Biomes.OCEAN)
                .add(Biomes.COLD_OCEAN)
                .add(Biomes.DEEP_COLD_OCEAN)
                .add(Biomes.DEEP_FROZEN_OCEAN)
                .add(Biomes.DEEP_LUKEWARM_OCEAN)
                .add(Biomes.DEEP_OCEAN)
                .add(Biomes.FROZEN_OCEAN)
                .add(Biomes.LUKEWARM_OCEAN)
                .add(Biomes.WARM_OCEAN);
        tag(TBATags.Biomes.HAS_ENDERBARK)
                .add(Biomes.END_HIGHLANDS)
                .add(Biomes.END_MIDLANDS)
                .add(Biomes.END_BARRENS)
                .add(Biomes.THE_END);
        tag(TBATags.Biomes.HAS_BLOODSHROOM)
                .add(Biomes.BASALT_DELTAS)
                .add(Biomes.SOUL_SAND_VALLEY)
                .add(Biomes.WARPED_FOREST)
                .add(Biomes.CRIMSON_FOREST)
                .add(Biomes.NETHER_WASTES)
                .addOptional(BOPBiomes.UNDERGROWTH.location());
        tag(TBATags.Biomes.HAS_GOLDEN_OAK)
                .addOptional(AetherBiomes.SKYROOT_GROVE.location());
        tag(TBATags.Biomes.HAS_AETHER_SKYROOT)
                .addOptional(AetherBiomes.SKYROOT_WOODLAND.location())
                .addOptional(AetherBiomes.SKYROOT_MEADOW.location())
                .addOptional(AetherBiomes.SKYROOT_GROVE.location())
                .addOptional(AetherBiomes.SKYROOT_FOREST.location());
        tag(TBATags.Biomes.HAS_PREAM)
                .add(Biomes.END_HIGHLANDS)
                .add(Biomes.END_MIDLANDS)
                .add(Biomes.END_BARRENS)
                .add(Biomes.THE_END);
        tag(TBATags.Biomes.HAS_EBONY)
                .add(Biomes.END_HIGHLANDS)
                .add(Biomes.END_MIDLANDS)
                .add(Biomes.END_BARRENS)
                .add(Biomes.THE_END);
        tag(TBATags.Biomes.HAS_CHORUS_NEST)
                .add(Biomes.END_HIGHLANDS)
                .add(Biomes.END_MIDLANDS)
                .add(Biomes.END_BARRENS)
                .add(Biomes.THE_END);
        tag(TBATags.Biomes.HAS_AZALEA)
                .add(Biomes.LUSH_CAVES);
        tag(TBATags.Biomes.HAS_COCONUT)
                .add(Biomes.BEACH);
        tag(TBATags.Biomes.HAS_HELLBARK)
                .addOptional(BOPBiomes.UNDERGROWTH.location());
        tag(TBATags.Biomes.HAS_UMBRAN)
                .addOptional(BOPBiomes.OMINOUS_WOODS.location());
        tag(TBATags.Biomes.HAS_MAGIC)
                .addOptional(BOPBiomes.MYSTIC_GROVE.location());
        tag(TBATags.Biomes.HAS_DEAD)
                .addOptional(BOPBiomes.TUNDRA.location())
                .addOptional(BOPBiomes.WOODED_WASTELAND.location())
                .addOptional(BOPBiomes.OMINOUS_WOODS.location())
                .addOptional(BOPBiomes.MUSKEG.location())
                .addOptional(BOPBiomes.OLD_GROWTH_DEAD_FOREST.location())
                .addOptional(BOPBiomes.DEAD_FOREST.location());
        tag(TBATags.Biomes.HAS_WILLOW)
                .addOptional(BOPBiomes.WETLAND.location())
                .addOptional(BOPBiomes.BAYOU.location());
        tag(TBATags.Biomes.HAS_PALM)
                .addOptional(BOPBiomes.TROPICS.location());
        tag(TBATags.Biomes.HAS_JACARANDA)
                .addOptional(BOPBiomes.LAVENDER_FOREST.location())
                .addOptional(BOPBiomes.LAVENDER_FIELD.location());
        tag(TBATags.Biomes.HAS_MAHOGANY)
                .addOptional(BOPBiomes.ROCKY_RAINFOREST.location())
                .addOptional(BOPBiomes.RAINFOREST.location());
        tag(TBATags.Biomes.HAS_CHERRY)
                .addOptional(BOPBiomes.BAMBOO_GROVE.location())
                .addOptional(BOPBiomes.CHERRY_BLOSSOM_GROVE.location());
        tag(TBATags.Biomes.HAS_REDWOOD)
                .addOptional(BOPBiomes.REDWOOD_FOREST.location());
        tag(TBATags.Biomes.HAS_FIR)
                .addOptional(BOPBiomes.SNOWY_CONIFEROUS_FOREST.location())
                .addOptional(BOPBiomes.SNOWY_FIR_CLEARING.location())
                .addOptional(BOPBiomes.FIR_CLEARING.location())
                .addOptional(BOPBiomes.CONIFEROUS_FOREST.location())
                .addOptional(BOPBiomes.AURORAL_GARDEN.location());
        tag(TBATags.Biomes.HAS_SUNFLOWER)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.ICE_SPIKES);
        tag(TBATags.Biomes.HAS_PEONY)
                .addOptional(BOPBiomes.CHERRY_BLOSSOM_GROVE.location())
                .addOptional(BOPBiomes.MEDITERRANEAN_FOREST.location())
                .add(Biomes.OLD_GROWTH_BIRCH_FOREST)
                .add(Biomes.FOREST)
                .add(Biomes.DARK_FOREST)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.BIRCH_FOREST);
        tag(TBATags.Biomes.HAS_ROSE_BUSH)
                .addOptional(BOPBiomes.TROPICS.location())
                .addOptional(BOPBiomes.FIELD.location())
                .addOptional(BOPBiomes.FORESTED_FIELD.location())
                .addOptional(BOPBiomes.LUSH_SAVANNA.location())
                .addOptional(BOPBiomes.OLD_GROWTH_WOODLAND.location())
                .addOptional(BOPBiomes.ORCHARD.location())
                .addOptional(BOPBiomes.WOODLAND.location())
                .add(Biomes.OLD_GROWTH_BIRCH_FOREST)
                .add(Biomes.FOREST)
                .add(Biomes.DARK_FOREST)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.BIRCH_FOREST);
        tag(TBATags.Biomes.HAS_LILAC)
                .addOptional(BOPBiomes.BAMBOO_GROVE.location())
                .addOptional(BOPBiomes.CHERRY_BLOSSOM_GROVE.location())
                .addOptional(BOPBiomes.FIELD.location())
                .addOptional(BOPBiomes.FORESTED_FIELD.location())
                .addOptional(BOPBiomes.MYSTIC_GROVE.location())
                .addOptional(BOPBiomes.ROCKY_SHRUBLAND.location())
                .add(Biomes.OLD_GROWTH_BIRCH_FOREST)
                .add(Biomes.FOREST)
                .add(Biomes.DARK_FOREST)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.BIRCH_FOREST);
        tag(TBATags.Biomes.HAS_BUTTERCUP)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.MEADOW)
                .add(Biomes.SUNFLOWER_PLAINS);
        tag(TBATags.Biomes.HAS_LILY_OF_THE_VALLEY)
                .addOptional(BOPBiomes.HIGHLAND.location())
                .addOptional(BOPBiomes.BAMBOO_GROVE.location())
                .addOptional(BOPBiomes.CHERRY_BLOSSOM_GROVE.location())
                .addOptional(BOPBiomes.FIELD.location())
                .addOptional(BOPBiomes.HIGHLAND_MOOR.location())
                .add(Biomes.OLD_GROWTH_BIRCH_FOREST)
                .add(Biomes.FOREST)
                .add(Biomes.DARK_FOREST)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.BIRCH_FOREST);
        tag(TBATags.Biomes.HAS_CORNFLOWER)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(TBATags.Biomes.HAS_OXEYE_DAISY)
                .addOptional(BOPBiomes.FLOODPLAIN.location())
                .addOptional(BOPBiomes.CONIFEROUS_FOREST.location())
                .addOptional(BOPBiomes.FIR_CLEARING.location())
                .addOptional(BOPBiomes.FLOODPLAIN.location())
                .addOptional(BOPBiomes.MEDITERRANEAN_FOREST.location())
                .addOptional(BOPBiomes.OLD_GROWTH_WOODLAND.location())
                .addOptional(BOPBiomes.ORCHARD.location())
                .addOptional(BOPBiomes.WOODLAND.location())
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(TBATags.Biomes.HAS_PINK_TULIP)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(TBATags.Biomes.HAS_WHITE_TULIP)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(TBATags.Biomes.HAS_ORANGE_TULIP)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(TBATags.Biomes.HAS_RED_TULIP)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(TBATags.Biomes.HAS_RED_TULIP)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .add(Biomes.PLAINS)
                .add(Biomes.SUNFLOWER_PLAINS)
                .add(Biomes.MEADOW);
        tag(TBATags.Biomes.HAS_ALLIUM)
                .addOptional(BOPBiomes.DRYLAND.location())
                .addOptional(BOPBiomes.SHRUBLAND.location())
                .addOptional(BOPBiomes.SCRUBLAND.location())
                .addOptional(BOPBiomes.HIGHLAND.location())
                .addOptional(BOPBiomes.HIGHLAND_MOOR.location())
                .addOptional(BOPBiomes.MYSTIC_GROVE.location())
                .addOptional(BOPBiomes.ORIGIN_VALLEY.location())
                .addOptional(BOPBiomes.ROCKY_SHRUBLAND.location())
                .addOptional(BOPBiomes.WOODED_SCRUBLAND.location())
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.MEADOW);
        tag(TBATags.Biomes.HAS_BLUE_ORCHID)
                .addOptional(BOPBiomes.HIGHLAND.location())
                .add(Biomes.SWAMP);
        tag(TBATags.Biomes.HAS_DARK_OAK)
                .addOptional(BOPBiomes.PUMPKIN_PATCH.location())
                .addOptional(BOPBiomes.SEASONAL_FOREST.location())
                .addOptional(BOPBiomes.VOLCANIC_PLAINS.location())
                .add(Biomes.DARK_FOREST);
        tag(TBATags.Biomes.HAS_BIRCH)
                .addOptional(BOPBiomes.HIGHLAND_MOOR.location())
                .add(Biomes.OLD_GROWTH_BIRCH_FOREST)
                .add(Biomes.BIRCH_FOREST)
                .add(Biomes.FLOWER_FOREST)
                .add(Biomes.FOREST);
        tag(TBATags.Biomes.HAS_JUNGLE)
                .addOptional(BOPBiomes.FUNGAL_JUNGLE.location())
                .addOptional(BOPBiomes.RAINFOREST.location())
                .addOptional(BOPBiomes.ROCKY_RAINFOREST.location())
                .addOptional(BOPBiomes.TROPICS.location())
                .add(Biomes.SPARSE_JUNGLE)
                .add(Biomes.BAMBOO_JUNGLE)
                .add(Biomes.JUNGLE);
        tag(TBATags.Biomes.HAS_ACACIA)
                .addOptional(BOPBiomes.WOODED_WASTELAND.location())
                .add(Biomes.WINDSWEPT_SAVANNA)
                .add(Biomes.SAVANNA_PLATEAU)
                .add(Biomes.SAVANNA);
        tag(TBATags.Biomes.HAS_MANGROVE)
                .add(Biomes.MANGROVE_SWAMP);
        tag(TBATags.Biomes.HAS_SPRUCE)
                .addOptional(BOPBiomes.SNOWY_FIR_CLEARING.location())
                .addOptional(BOPBiomes.SNOWY_CONIFEROUS_FOREST.location())
                .addOptional(BOPBiomes.OLD_GROWTH_DEAD_FOREST.location())
                .addOptional(BOPBiomes.FIELD.location())
                .addOptional(BOPBiomes.MAPLE_WOODS.location())
                .addOptional(BOPBiomes.FORESTED_FIELD.location())
                .addOptional(BOPBiomes.JADE_CLIFFS.location())
                .addOptional(BOPBiomes.MEDITERRANEAN_FOREST.location())
                .addOptional(BOPBiomes.SNOWY_MAPLE_WOODS.location())
                .addOptional(BOPBiomes.WETLAND.location())
                .addOptional(BOPBiomes.WOODED_SCRUBLAND.location())
                .add(Biomes.TAIGA)
                .add(Biomes.FROZEN_RIVER)
                .add(Biomes.SNOWY_BEACH)
                .add(Biomes.FROZEN_PEAKS)
                .add(Biomes.GROVE)
                .add(Biomes.SNOWY_PLAINS)
                .add(Biomes.ICE_SPIKES)
                .add(Biomes.JAGGED_PEAKS)
                .add(Biomes.SNOWY_SLOPES)
                .add(Biomes.SNOWY_TAIGA)
                .add(Biomes.WINDSWEPT_HILLS)
                .add(Biomes.WINDSWEPT_GRAVELLY_HILLS)
                .add(Biomes.WINDSWEPT_FOREST)
                .add(Biomes.OLD_GROWTH_SPRUCE_TAIGA)
                .add(Biomes.OLD_GROWTH_PINE_TAIGA);
        tag(TBATags.Biomes.NETHER_BIOMES)
                .add(Biomes.BASALT_DELTAS)
                .add(Biomes.NETHER_WASTES)
                .add(Biomes.WARPED_FOREST)
                .add(Biomes.CRIMSON_FOREST)
                .add(Biomes.SOUL_SAND_VALLEY);
        tag(TBATags.Biomes.HAS_WARPED_FUNGUS)
                .add(Biomes.WARPED_FOREST);
        tag(TBATags.Biomes.HAS_CRIMSON_FUNGUS)
                .add(Biomes.CRIMSON_FOREST);
        tag(TBATags.Biomes.HAS_SANDSTONE)
                .addOptional(BOPBiomes.WASTELAND.location())
                .add(Biomes.SNOWY_BEACH)
                .add(Biomes.BEACH)
                .add(Biomes.DESERT);
        tag(TBATags.Biomes.HAS_RED_SANDSTONE)
                .add(Biomes.WOODED_BADLANDS)
                .add(Biomes.ERODED_BADLANDS)
                .add(Biomes.BADLANDS);
        tag(TBATags.Biomes.HAS_MOSSY_STONE)
                .addOptional(BOPBiomes.TUNDRA.location())
                .add(Biomes.TAIGA)
                .add(Biomes.OLD_GROWTH_PINE_TAIGA)
                .add(Biomes.OLD_GROWTH_SPRUCE_TAIGA);
        tag(TBATags.Biomes.HAS_PUFFERFISH)
                .add(Biomes.LUKEWARM_OCEAN)
                .add(Biomes.DEEP_LUKEWARM_OCEAN)
                .add(Biomes.WARM_OCEAN);
        tag(TBATags.Biomes.HAS_TROPICAL_FISH)
                .add(Biomes.LUSH_CAVES)
                .add(Biomes.MANGROVE_SWAMP)
                .add(Biomes.LUKEWARM_OCEAN)
                .add(Biomes.DEEP_LUKEWARM_OCEAN)
                .add(Biomes.WARM_OCEAN);
        tag(TBATags.Biomes.HAS_SALMON)
                .add(Biomes.RIVER)
                .add(Biomes.FROZEN_RIVER)
                .add(Biomes.COLD_OCEAN)
                .add(Biomes.DEEP_COLD_OCEAN)
                .add(Biomes.FROZEN_OCEAN)
                .add(Biomes.DEEP_FROZEN_OCEAN);
        tag(TBATags.Biomes.HAS_FROGS)
                .addOptional(BOPBiomes.BOG.location())
                .add(Biomes.SWAMP)
                .add(Biomes.MANGROVE_SWAMP);
        tag(TBATags.Biomes.HAS_AXOLOTL)
                .add(Biomes.LUSH_CAVES);
        tag(TBATags.Biomes.HAS_MUD)
                .addOptional(BOPBiomes.GLOWING_GROTTO.location())
                .addOptional(BOPBiomes.WETLAND.location())
                .add(Biomes.MANGROVE_SWAMP);
        tag(TBATags.Biomes.IS_ARID)
                .add(Biomes.DESERT)
                .add(Biomes.SAVANNA)
                .add(Biomes.SAVANNA_PLATEAU)
                .add(Biomes.BADLANDS)
                .add(Biomes.WOODED_BADLANDS)
                .add(Biomes.WINDSWEPT_SAVANNA)
                .add(Biomes.ERODED_BADLANDS)
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:wooded_scrubland")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:wasteland")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:volcano")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:shrubland")))
                .addOptional(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:dryland")));
        tag(TBATags.Biomes.IS_TROPICAL)
                .addOptionalTag(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:tropics")))
                .addOptionalTag(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:tropics")))
                .addOptionalTag(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:rocky_rainforest")))
                .addOptionalTag(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:rainforest")))
                .addOptionalTag(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:fungal_jungle")))
                .addOptionalTag(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:floodplain")))
                .addOptionalTag(Objects.requireNonNull(
                        ResourceLocation.tryParse("biomesoplenty:bayou")))
                .add(Biomes.MANGROVE_SWAMP)
                .add(Biomes.JUNGLE)
                .add(Biomes.SPARSE_JUNGLE)
                .add(Biomes.BAMBOO_JUNGLE);
        tag(Tags.Biomes.IS_WET_OVERWORLD)
                .addTag(TBATags.Biomes.IS_TROPICAL);
        tag(Tags.Biomes.IS_HOT_OVERWORLD)
                .addTag(TBATags.Biomes.IS_TROPICAL);
        tag(TBATags.Biomes.HAS_SKY_SLIME_POOLS)
                .add(TBABiomes.TBA_UNDERDEEP)
                .add(TBABiomes.TBA_AETHER_INCURSION);
        tag(TBATags.Biomes.HAS_ICHOR_SLIME_POOLS)
                .add(TBABiomes.TBA_NETHER_CORRUPTION);
        tag(TBATags.Biomes.HAS_ENDER_SLIME_POOLS)
                .add(TBABiomes.TBA_ENDER_EROSION);
        tag(TBATags.Biomes.HAS_SWET_POOLS)
                .add(TBABiomes.TBA_AETHER_INCURSION);
        tag(TBATags.Biomes.HAS_EARTH_SLIME_POOLS)
                .addTag(TBATags.Biomes.TBA_MINING_BIOMES);
        tag(TBATags.Biomes.HAS_CLAY_SLIME_POOLS)
                .add(TBABiomes.TBA_UNDERDEEP)
                .add(TBABiomes.TBA_SLIME_CAVES);
        tag(TBATags.Biomes.HAS_NETHER_FOSSIL)
                .add(TBABiomes.TBA_AETHER_INCURSION)
                .add(TBABiomes.TBA_ENDER_EROSION)
                .add(TBABiomes.TBA_NETHER_CORRUPTION)
                .add(TBABiomes.TBA_SLIME_CAVES);
        tag(TBATags.Biomes.HAS_CAMP_UNDERGROUND)
                .addTag(TBATags.Biomes.UNDERGROUND_BUT_NOT_DEEP_DARK);
        tag(TBATags.Biomes.TBA_MINING_BIOMES)
                .add(TBABiomes.TBA_UNDERDEEP)
                .add(TBABiomes.TBA_AETHER_INCURSION)
                .add(TBABiomes.TBA_ENDER_EROSION)
                .add(TBABiomes.TBA_NETHER_CORRUPTION)
                .add(TBABiomes.TBA_SLIME_CAVES);
        tag(TBATags.Biomes.UNDERGROUND_BUT_NOT_DEEP_DARK)
                .addTag(TBATags.Biomes.TBA_MINING_BIOMES)
                .add(Biomes.LUSH_CAVES)
                .add(Biomes.DRIPSTONE_CAVES)
                .addOptional(BOPBiomes.SPIDER_NEST.location())
                .addOptional(BOPBiomes.GLOWING_GROTTO.location());
        tag(TBATags.Biomes.IS_CAVE)
                .addTag(TBATags.Biomes.TBA_MINING_BIOMES)
                .add(Biomes.LUSH_CAVES)
                .add(Biomes.DRIPSTONE_CAVES)
                .add(Biomes.DEEP_DARK)
                .addOptional(BOPBiomes.SPIDER_NEST.location())
                .addOptional(BOPBiomes.GLOWING_GROTTO.location());
        tag(TBATags.Biomes.IS_UNDERGROUND)
                .addTag(TBATags.Biomes.IS_CAVE);
        tag(BiomeTags.HAS_MINESHAFT)
                .addTag(TBATags.Biomes.TBA_MINING_BIOMES);
    }
}