package com.github.warrentode.turtleblockacademy.datagen.tags;

import biomesoplenty.api.block.BOPBlocks;
import com.github.warrentode.turtleblockacademy.blocks.TBABlocks;
import com.github.warrentode.turtleblockacademy.util.TBATags;
import net.mcreator.festivedelight.init.FestiveDelightModBlocks;
import net.mcreator.moadecorcookery.init.MoaDecorCookeryModItems;
import net.mcreator.phantasm.init.PhantasmModBlocks;
import net.mcreator.phantasm.init.PhantasmModItems;
import net.mcreator.unusualend.init.UnusualendModItems;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.tags.BlockTagsProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.Objects;

import static net.minecraft.tags.BlockTags.NEEDS_STONE_TOOL;

public class BlockTagsGen extends BlockTagsProvider {
    public BlockTagsGen(DataGenerator generator, String modid, @Nullable ExistingFileHelper helper) {
        super(generator, modid, helper);
    }

    @Override
    protected void addTags() {
        this.registerTBATags();
        this.registerMinecraftTags();
        this.registerBlockMineables();
    }

    private void registerMinecraftTags() {
        tag(TBATags.Blocks.NEEDS_NETHERITE_TOOL)
                .add(Blocks.REINFORCED_DEEPSLATE);
        tag(NEEDS_STONE_TOOL)
                .add(Blocks.BUDDING_AMETHYST);
    }

    private void registerBlockMineables() {
        tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(Blocks.BUDDING_AMETHYST)
                .add(Blocks.REINFORCED_DEEPSLATE);
    }

    protected void registerTBATags() {
        tag(TBATags.Blocks.FURNITURE)
                .addTag(TBATags.Blocks.DESKS)
                .addTag(TBATags.Blocks.DESK_CABINETS)
                .addTag(TBATags.Blocks.TABLES)
                .addTag(TBATags.Blocks.CHAIRS)
                .addTag(TBATags.Blocks.BENCHES)
                .addTag(TBATags.Blocks.LOCKERS)
                .addTag(TBATags.Blocks.PLATES)
                .addTag(TBATags.Blocks.BOOKCASES)
                .addTag(TBATags.Blocks.BASKETS);
        tag(TBATags.Blocks.BASKETS)

                .add(
                        TBABlocks.BASKET_OAK_WHITE.get(),
                        TBABlocks.BASKET_OAK_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_OAK_GRAY.get(),
                        TBABlocks.BASKET_OAK_BLACK.get(),
                        TBABlocks.BASKET_OAK_BROWN.get(),
                        TBABlocks.BASKET_OAK_RED.get(),
                        TBABlocks.BASKET_OAK_ORANGE.get(),
                        TBABlocks.BASKET_OAK_YELLOW.get(),
                        TBABlocks.BASKET_OAK_LIME.get(),
                        TBABlocks.BASKET_OAK_GREEN.get(),
                        TBABlocks.BASKET_OAK_CYAN.get(),
                        TBABlocks.BASKET_OAK_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_OAK_BLUE.get(),
                        TBABlocks.BASKET_OAK_PURPLE.get(),
                        TBABlocks.BASKET_OAK_MAGENTA.get(),
                        TBABlocks.BASKET_OAK_PINK.get(),
                        TBABlocks.BASKET_BIRCH_WHITE.get(),
                        TBABlocks.BASKET_BIRCH_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_BIRCH_GRAY.get(),
                        TBABlocks.BASKET_BIRCH_BLACK.get(),
                        TBABlocks.BASKET_BIRCH_BROWN.get(),
                        TBABlocks.BASKET_BIRCH_RED.get(),
                        TBABlocks.BASKET_BIRCH_ORANGE.get(),
                        TBABlocks.BASKET_BIRCH_YELLOW.get(),
                        TBABlocks.BASKET_BIRCH_LIME.get(),
                        TBABlocks.BASKET_BIRCH_GREEN.get(),
                        TBABlocks.BASKET_BIRCH_CYAN.get(),
                        TBABlocks.BASKET_BIRCH_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_BIRCH_BLUE.get(),
                        TBABlocks.BASKET_BIRCH_PURPLE.get(),
                        TBABlocks.BASKET_BIRCH_MAGENTA.get(),
                        TBABlocks.BASKET_BIRCH_PINK.get(),
                        TBABlocks.BASKET_SPRUCE_WHITE.get(),
                        TBABlocks.BASKET_SPRUCE_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_SPRUCE_GRAY.get(),
                        TBABlocks.BASKET_SPRUCE_BLACK.get(),
                        TBABlocks.BASKET_SPRUCE_BROWN.get(),
                        TBABlocks.BASKET_SPRUCE_RED.get(),
                        TBABlocks.BASKET_SPRUCE_ORANGE.get(),
                        TBABlocks.BASKET_SPRUCE_YELLOW.get(),
                        TBABlocks.BASKET_SPRUCE_LIME.get(),
                        TBABlocks.BASKET_SPRUCE_GREEN.get(),
                        TBABlocks.BASKET_SPRUCE_CYAN.get(),
                        TBABlocks.BASKET_SPRUCE_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_SPRUCE_BLUE.get(),
                        TBABlocks.BASKET_SPRUCE_PURPLE.get(),
                        TBABlocks.BASKET_SPRUCE_MAGENTA.get(),
                        TBABlocks.BASKET_SPRUCE_PINK.get(),
                        TBABlocks.BASKET_JUNGLE_WHITE.get(),
                        TBABlocks.BASKET_JUNGLE_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_JUNGLE_GRAY.get(),
                        TBABlocks.BASKET_JUNGLE_BLACK.get(),
                        TBABlocks.BASKET_JUNGLE_BROWN.get(),
                        TBABlocks.BASKET_JUNGLE_RED.get(),
                        TBABlocks.BASKET_JUNGLE_ORANGE.get(),
                        TBABlocks.BASKET_JUNGLE_YELLOW.get(),
                        TBABlocks.BASKET_JUNGLE_LIME.get(),
                        TBABlocks.BASKET_JUNGLE_GREEN.get(),
                        TBABlocks.BASKET_JUNGLE_CYAN.get(),
                        TBABlocks.BASKET_JUNGLE_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_JUNGLE_BLUE.get(),
                        TBABlocks.BASKET_JUNGLE_PURPLE.get(),
                        TBABlocks.BASKET_JUNGLE_MAGENTA.get(),
                        TBABlocks.BASKET_JUNGLE_PINK.get(),
                        TBABlocks.BASKET_ACACIA_WHITE.get(),
                        TBABlocks.BASKET_ACACIA_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_ACACIA_GRAY.get(),
                        TBABlocks.BASKET_ACACIA_BLACK.get(),
                        TBABlocks.BASKET_ACACIA_BROWN.get(),
                        TBABlocks.BASKET_ACACIA_RED.get(),
                        TBABlocks.BASKET_ACACIA_ORANGE.get(),
                        TBABlocks.BASKET_ACACIA_YELLOW.get(),
                        TBABlocks.BASKET_ACACIA_LIME.get(),
                        TBABlocks.BASKET_ACACIA_GREEN.get(),
                        TBABlocks.BASKET_ACACIA_CYAN.get(),
                        TBABlocks.BASKET_ACACIA_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_ACACIA_BLUE.get(),
                        TBABlocks.BASKET_ACACIA_PURPLE.get(),
                        TBABlocks.BASKET_ACACIA_MAGENTA.get(),
                        TBABlocks.BASKET_ACACIA_PINK.get(),
                        TBABlocks.BASKET_DARK_OAK_WHITE.get(),
                        TBABlocks.BASKET_DARK_OAK_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_DARK_OAK_GRAY.get(),
                        TBABlocks.BASKET_DARK_OAK_BLACK.get(),
                        TBABlocks.BASKET_DARK_OAK_BROWN.get(),
                        TBABlocks.BASKET_DARK_OAK_RED.get(),
                        TBABlocks.BASKET_DARK_OAK_ORANGE.get(),
                        TBABlocks.BASKET_DARK_OAK_YELLOW.get(),
                        TBABlocks.BASKET_DARK_OAK_LIME.get(),
                        TBABlocks.BASKET_DARK_OAK_GREEN.get(),
                        TBABlocks.BASKET_DARK_OAK_CYAN.get(),
                        TBABlocks.BASKET_DARK_OAK_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_DARK_OAK_BLUE.get(),
                        TBABlocks.BASKET_DARK_OAK_PURPLE.get(),
                        TBABlocks.BASKET_DARK_OAK_MAGENTA.get(),
                        TBABlocks.BASKET_DARK_OAK_PINK.get(),
                        TBABlocks.BASKET_MANGROVE_WHITE.get(),
                        TBABlocks.BASKET_MANGROVE_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_MANGROVE_GRAY.get(),
                        TBABlocks.BASKET_MANGROVE_BLACK.get(),
                        TBABlocks.BASKET_MANGROVE_BROWN.get(),
                        TBABlocks.BASKET_MANGROVE_RED.get(),
                        TBABlocks.BASKET_MANGROVE_ORANGE.get(),
                        TBABlocks.BASKET_MANGROVE_YELLOW.get(),
                        TBABlocks.BASKET_MANGROVE_LIME.get(),
                        TBABlocks.BASKET_MANGROVE_GREEN.get(),
                        TBABlocks.BASKET_MANGROVE_CYAN.get(),
                        TBABlocks.BASKET_MANGROVE_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_MANGROVE_BLUE.get(),
                        TBABlocks.BASKET_MANGROVE_PURPLE.get(),
                        TBABlocks.BASKET_MANGROVE_MAGENTA.get(),
                        TBABlocks.BASKET_MANGROVE_PINK.get(),
                        TBABlocks.BASKET_CRIMSON_WHITE.get(),
                        TBABlocks.BASKET_CRIMSON_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_CRIMSON_GRAY.get(),
                        TBABlocks.BASKET_CRIMSON_BLACK.get(),
                        TBABlocks.BASKET_CRIMSON_BROWN.get(),
                        TBABlocks.BASKET_CRIMSON_RED.get(),
                        TBABlocks.BASKET_CRIMSON_ORANGE.get(),
                        TBABlocks.BASKET_CRIMSON_YELLOW.get(),
                        TBABlocks.BASKET_CRIMSON_LIME.get(),
                        TBABlocks.BASKET_CRIMSON_GREEN.get(),
                        TBABlocks.BASKET_CRIMSON_CYAN.get(),
                        TBABlocks.BASKET_CRIMSON_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_CRIMSON_BLUE.get(),
                        TBABlocks.BASKET_CRIMSON_PURPLE.get(),
                        TBABlocks.BASKET_CRIMSON_MAGENTA.get(),
                        TBABlocks.BASKET_CRIMSON_PINK.get(),
                        TBABlocks.BASKET_WARPED_WHITE.get(),
                        TBABlocks.BASKET_WARPED_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_WARPED_GRAY.get(),
                        TBABlocks.BASKET_WARPED_BLACK.get(),
                        TBABlocks.BASKET_WARPED_BROWN.get(),
                        TBABlocks.BASKET_WARPED_RED.get(),
                        TBABlocks.BASKET_WARPED_ORANGE.get(),
                        TBABlocks.BASKET_WARPED_YELLOW.get(),
                        TBABlocks.BASKET_WARPED_LIME.get(),
                        TBABlocks.BASKET_WARPED_GREEN.get(),
                        TBABlocks.BASKET_WARPED_CYAN.get(),
                        TBABlocks.BASKET_WARPED_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_WARPED_BLUE.get(),
                        TBABlocks.BASKET_WARPED_PURPLE.get(),
                        TBABlocks.BASKET_WARPED_MAGENTA.get(),
                        TBABlocks.BASKET_WARPED_PINK.get(),
                        TBABlocks.BASKET_FIR_WHITE.get(),
                        TBABlocks.BASKET_FIR_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_FIR_GRAY.get(),
                        TBABlocks.BASKET_FIR_BLACK.get(),
                        TBABlocks.BASKET_FIR_BROWN.get(),
                        TBABlocks.BASKET_FIR_RED.get(),
                        TBABlocks.BASKET_FIR_ORANGE.get(),
                        TBABlocks.BASKET_FIR_YELLOW.get(),
                        TBABlocks.BASKET_FIR_LIME.get(),
                        TBABlocks.BASKET_FIR_GREEN.get(),
                        TBABlocks.BASKET_FIR_CYAN.get(),
                        TBABlocks.BASKET_FIR_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_FIR_BLUE.get(),
                        TBABlocks.BASKET_FIR_PURPLE.get(),
                        TBABlocks.BASKET_FIR_MAGENTA.get(),
                        TBABlocks.BASKET_FIR_PINK.get(),
                        TBABlocks.BASKET_REDWOOD_WHITE.get(),
                        TBABlocks.BASKET_REDWOOD_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_REDWOOD_GRAY.get(),
                        TBABlocks.BASKET_REDWOOD_BLACK.get(),
                        TBABlocks.BASKET_REDWOOD_BROWN.get(),
                        TBABlocks.BASKET_REDWOOD_RED.get(),
                        TBABlocks.BASKET_REDWOOD_ORANGE.get(),
                        TBABlocks.BASKET_REDWOOD_YELLOW.get(),
                        TBABlocks.BASKET_REDWOOD_LIME.get(),
                        TBABlocks.BASKET_REDWOOD_GREEN.get(),
                        TBABlocks.BASKET_REDWOOD_CYAN.get(),
                        TBABlocks.BASKET_REDWOOD_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_REDWOOD_BLUE.get(),
                        TBABlocks.BASKET_REDWOOD_PURPLE.get(),
                        TBABlocks.BASKET_REDWOOD_MAGENTA.get(),
                        TBABlocks.BASKET_REDWOOD_PINK.get(),
                        TBABlocks.BASKET_CHERRY_WHITE.get(),
                        TBABlocks.BASKET_CHERRY_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_CHERRY_GRAY.get(),
                        TBABlocks.BASKET_CHERRY_BLACK.get(),
                        TBABlocks.BASKET_CHERRY_BROWN.get(),
                        TBABlocks.BASKET_CHERRY_RED.get(),
                        TBABlocks.BASKET_CHERRY_ORANGE.get(),
                        TBABlocks.BASKET_CHERRY_YELLOW.get(),
                        TBABlocks.BASKET_CHERRY_LIME.get(),
                        TBABlocks.BASKET_CHERRY_GREEN.get(),
                        TBABlocks.BASKET_CHERRY_CYAN.get(),
                        TBABlocks.BASKET_CHERRY_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_CHERRY_BLUE.get(),
                        TBABlocks.BASKET_CHERRY_PURPLE.get(),
                        TBABlocks.BASKET_CHERRY_MAGENTA.get(),
                        TBABlocks.BASKET_CHERRY_PINK.get(),
                        TBABlocks.BASKET_MAHOGANY_WHITE.get(),
                        TBABlocks.BASKET_MAHOGANY_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_MAHOGANY_GRAY.get(),
                        TBABlocks.BASKET_MAHOGANY_BLACK.get(),
                        TBABlocks.BASKET_MAHOGANY_BROWN.get(),
                        TBABlocks.BASKET_MAHOGANY_RED.get(),
                        TBABlocks.BASKET_MAHOGANY_ORANGE.get(),
                        TBABlocks.BASKET_MAHOGANY_YELLOW.get(),
                        TBABlocks.BASKET_MAHOGANY_LIME.get(),
                        TBABlocks.BASKET_MAHOGANY_GREEN.get(),
                        TBABlocks.BASKET_MAHOGANY_CYAN.get(),
                        TBABlocks.BASKET_MAHOGANY_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_MAHOGANY_BLUE.get(),
                        TBABlocks.BASKET_MAHOGANY_PURPLE.get(),
                        TBABlocks.BASKET_MAHOGANY_MAGENTA.get(),
                        TBABlocks.BASKET_MAHOGANY_PINK.get(),
                        TBABlocks.BASKET_JACARANDA_WHITE.get(),
                        TBABlocks.BASKET_JACARANDA_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_JACARANDA_GRAY.get(),
                        TBABlocks.BASKET_JACARANDA_BLACK.get(),
                        TBABlocks.BASKET_JACARANDA_BROWN.get(),
                        TBABlocks.BASKET_JACARANDA_RED.get(),
                        TBABlocks.BASKET_JACARANDA_ORANGE.get(),
                        TBABlocks.BASKET_JACARANDA_YELLOW.get(),
                        TBABlocks.BASKET_JACARANDA_LIME.get(),
                        TBABlocks.BASKET_JACARANDA_GREEN.get(),
                        TBABlocks.BASKET_JACARANDA_CYAN.get(),
                        TBABlocks.BASKET_JACARANDA_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_JACARANDA_BLUE.get(),
                        TBABlocks.BASKET_JACARANDA_PURPLE.get(),
                        TBABlocks.BASKET_JACARANDA_MAGENTA.get(),
                        TBABlocks.BASKET_JACARANDA_PINK.get(),
                        TBABlocks.BASKET_PALM_WHITE.get(),
                        TBABlocks.BASKET_PALM_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_PALM_GRAY.get(),
                        TBABlocks.BASKET_PALM_BLACK.get(),
                        TBABlocks.BASKET_PALM_BROWN.get(),
                        TBABlocks.BASKET_PALM_RED.get(),
                        TBABlocks.BASKET_PALM_ORANGE.get(),
                        TBABlocks.BASKET_PALM_YELLOW.get(),
                        TBABlocks.BASKET_PALM_LIME.get(),
                        TBABlocks.BASKET_PALM_GREEN.get(),
                        TBABlocks.BASKET_PALM_CYAN.get(),
                        TBABlocks.BASKET_PALM_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_PALM_BLUE.get(),
                        TBABlocks.BASKET_PALM_PURPLE.get(),
                        TBABlocks.BASKET_PALM_MAGENTA.get(),
                        TBABlocks.BASKET_PALM_PINK.get(),
                        TBABlocks.BASKET_WILLOW_WHITE.get(),
                        TBABlocks.BASKET_WILLOW_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_WILLOW_GRAY.get(),
                        TBABlocks.BASKET_WILLOW_BLACK.get(),
                        TBABlocks.BASKET_WILLOW_BROWN.get(),
                        TBABlocks.BASKET_WILLOW_RED.get(),
                        TBABlocks.BASKET_WILLOW_ORANGE.get(),
                        TBABlocks.BASKET_WILLOW_YELLOW.get(),
                        TBABlocks.BASKET_WILLOW_LIME.get(),
                        TBABlocks.BASKET_WILLOW_GREEN.get(),
                        TBABlocks.BASKET_WILLOW_CYAN.get(),
                        TBABlocks.BASKET_WILLOW_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_WILLOW_BLUE.get(),
                        TBABlocks.BASKET_WILLOW_PURPLE.get(),
                        TBABlocks.BASKET_WILLOW_MAGENTA.get(),
                        TBABlocks.BASKET_WILLOW_PINK.get(),
                        TBABlocks.BASKET_DEAD_WHITE.get(),
                        TBABlocks.BASKET_DEAD_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_DEAD_GRAY.get(),
                        TBABlocks.BASKET_DEAD_BLACK.get(),
                        TBABlocks.BASKET_DEAD_BROWN.get(),
                        TBABlocks.BASKET_DEAD_RED.get(),
                        TBABlocks.BASKET_DEAD_ORANGE.get(),
                        TBABlocks.BASKET_DEAD_YELLOW.get(),
                        TBABlocks.BASKET_DEAD_LIME.get(),
                        TBABlocks.BASKET_DEAD_GREEN.get(),
                        TBABlocks.BASKET_DEAD_CYAN.get(),
                        TBABlocks.BASKET_DEAD_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_DEAD_BLUE.get(),
                        TBABlocks.BASKET_DEAD_PURPLE.get(),
                        TBABlocks.BASKET_DEAD_MAGENTA.get(),
                        TBABlocks.BASKET_DEAD_PINK.get(),
                        TBABlocks.BASKET_MAGIC_WHITE.get(),
                        TBABlocks.BASKET_MAGIC_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_MAGIC_GRAY.get(),
                        TBABlocks.BASKET_MAGIC_BLACK.get(),
                        TBABlocks.BASKET_MAGIC_BROWN.get(),
                        TBABlocks.BASKET_MAGIC_RED.get(),
                        TBABlocks.BASKET_MAGIC_ORANGE.get(),
                        TBABlocks.BASKET_MAGIC_YELLOW.get(),
                        TBABlocks.BASKET_MAGIC_LIME.get(),
                        TBABlocks.BASKET_MAGIC_GREEN.get(),
                        TBABlocks.BASKET_MAGIC_CYAN.get(),
                        TBABlocks.BASKET_MAGIC_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_MAGIC_BLUE.get(),
                        TBABlocks.BASKET_MAGIC_PURPLE.get(),
                        TBABlocks.BASKET_MAGIC_MAGENTA.get(),
                        TBABlocks.BASKET_MAGIC_PINK.get(),
                        TBABlocks.BASKET_UMBRAN_WHITE.get(),
                        TBABlocks.BASKET_UMBRAN_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_UMBRAN_GRAY.get(),
                        TBABlocks.BASKET_UMBRAN_BLACK.get(),
                        TBABlocks.BASKET_UMBRAN_BROWN.get(),
                        TBABlocks.BASKET_UMBRAN_RED.get(),
                        TBABlocks.BASKET_UMBRAN_ORANGE.get(),
                        TBABlocks.BASKET_UMBRAN_YELLOW.get(),
                        TBABlocks.BASKET_UMBRAN_LIME.get(),
                        TBABlocks.BASKET_UMBRAN_GREEN.get(),
                        TBABlocks.BASKET_UMBRAN_CYAN.get(),
                        TBABlocks.BASKET_UMBRAN_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_UMBRAN_BLUE.get(),
                        TBABlocks.BASKET_UMBRAN_PURPLE.get(),
                        TBABlocks.BASKET_UMBRAN_MAGENTA.get(),
                        TBABlocks.BASKET_UMBRAN_PINK.get(),
                        TBABlocks.BASKET_HELLBARK_WHITE.get(),
                        TBABlocks.BASKET_HELLBARK_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_HELLBARK_GRAY.get(),
                        TBABlocks.BASKET_HELLBARK_BLACK.get(),
                        TBABlocks.BASKET_HELLBARK_BROWN.get(),
                        TBABlocks.BASKET_HELLBARK_RED.get(),
                        TBABlocks.BASKET_HELLBARK_ORANGE.get(),
                        TBABlocks.BASKET_HELLBARK_YELLOW.get(),
                        TBABlocks.BASKET_HELLBARK_LIME.get(),
                        TBABlocks.BASKET_HELLBARK_GREEN.get(),
                        TBABlocks.BASKET_HELLBARK_CYAN.get(),
                        TBABlocks.BASKET_HELLBARK_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_HELLBARK_BLUE.get(),
                        TBABlocks.BASKET_HELLBARK_PURPLE.get(),
                        TBABlocks.BASKET_HELLBARK_MAGENTA.get(),
                        TBABlocks.BASKET_HELLBARK_PINK.get(),
                        TBABlocks.BASKET_COCONUT_WHITE.get(),
                        TBABlocks.BASKET_COCONUT_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_COCONUT_GRAY.get(),
                        TBABlocks.BASKET_COCONUT_BLACK.get(),
                        TBABlocks.BASKET_COCONUT_BROWN.get(),
                        TBABlocks.BASKET_COCONUT_RED.get(),
                        TBABlocks.BASKET_COCONUT_ORANGE.get(),
                        TBABlocks.BASKET_COCONUT_YELLOW.get(),
                        TBABlocks.BASKET_COCONUT_LIME.get(),
                        TBABlocks.BASKET_COCONUT_GREEN.get(),
                        TBABlocks.BASKET_COCONUT_CYAN.get(),
                        TBABlocks.BASKET_COCONUT_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_COCONUT_BLUE.get(),
                        TBABlocks.BASKET_COCONUT_PURPLE.get(),
                        TBABlocks.BASKET_COCONUT_MAGENTA.get(),
                        TBABlocks.BASKET_COCONUT_PINK.get(),
                        TBABlocks.BASKET_WALNUT_WHITE.get(),
                        TBABlocks.BASKET_WALNUT_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_WALNUT_GRAY.get(),
                        TBABlocks.BASKET_WALNUT_BLACK.get(),
                        TBABlocks.BASKET_WALNUT_BROWN.get(),
                        TBABlocks.BASKET_WALNUT_RED.get(),
                        TBABlocks.BASKET_WALNUT_ORANGE.get(),
                        TBABlocks.BASKET_WALNUT_YELLOW.get(),
                        TBABlocks.BASKET_WALNUT_LIME.get(),
                        TBABlocks.BASKET_WALNUT_GREEN.get(),
                        TBABlocks.BASKET_WALNUT_CYAN.get(),
                        TBABlocks.BASKET_WALNUT_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_WALNUT_BLUE.get(),
                        TBABlocks.BASKET_WALNUT_PURPLE.get(),
                        TBABlocks.BASKET_WALNUT_MAGENTA.get(),
                        TBABlocks.BASKET_WALNUT_PINK.get(),
                        TBABlocks.BASKET_AZALEA_WHITE.get(),
                        TBABlocks.BASKET_AZALEA_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_AZALEA_GRAY.get(),
                        TBABlocks.BASKET_AZALEA_BLACK.get(),
                        TBABlocks.BASKET_AZALEA_BROWN.get(),
                        TBABlocks.BASKET_AZALEA_RED.get(),
                        TBABlocks.BASKET_AZALEA_ORANGE.get(),
                        TBABlocks.BASKET_AZALEA_YELLOW.get(),
                        TBABlocks.BASKET_AZALEA_LIME.get(),
                        TBABlocks.BASKET_AZALEA_GREEN.get(),
                        TBABlocks.BASKET_AZALEA_CYAN.get(),
                        TBABlocks.BASKET_AZALEA_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_AZALEA_BLUE.get(),
                        TBABlocks.BASKET_AZALEA_PURPLE.get(),
                        TBABlocks.BASKET_AZALEA_MAGENTA.get(),
                        TBABlocks.BASKET_AZALEA_PINK.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_WHITE.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_GRAY.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_BLACK.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_BROWN.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_RED.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_ORANGE.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_YELLOW.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_LIME.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_GREEN.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_CYAN.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_BLUE.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_PURPLE.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_MAGENTA.get(),
                        TBABlocks.BASKET_FLOWERING_AZALEA_PINK.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_WHITE.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_GRAY.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_BLACK.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_BROWN.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_RED.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_ORANGE.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_YELLOW.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_LIME.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_GREEN.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_CYAN.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_BLUE.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_PURPLE.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_MAGENTA.get(),
                        TBABlocks.BASKET_AETHER_SKYROOT_PINK.get(),
                        TBABlocks.BASKET_PREAM_WHITE.get(),
                        TBABlocks.BASKET_PREAM_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_PREAM_GRAY.get(),
                        TBABlocks.BASKET_PREAM_BLACK.get(),
                        TBABlocks.BASKET_PREAM_BROWN.get(),
                        TBABlocks.BASKET_PREAM_RED.get(),
                        TBABlocks.BASKET_PREAM_ORANGE.get(),
                        TBABlocks.BASKET_PREAM_YELLOW.get(),
                        TBABlocks.BASKET_PREAM_LIME.get(),
                        TBABlocks.BASKET_PREAM_GREEN.get(),
                        TBABlocks.BASKET_PREAM_CYAN.get(),
                        TBABlocks.BASKET_PREAM_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_PREAM_BLUE.get(),
                        TBABlocks.BASKET_PREAM_PURPLE.get(),
                        TBABlocks.BASKET_PREAM_MAGENTA.get(),
                        TBABlocks.BASKET_PREAM_PINK.get(),
                        TBABlocks.BASKET_EBONY_WHITE.get(),
                        TBABlocks.BASKET_EBONY_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_EBONY_GRAY.get(),
                        TBABlocks.BASKET_EBONY_BLACK.get(),
                        TBABlocks.BASKET_EBONY_BROWN.get(),
                        TBABlocks.BASKET_EBONY_RED.get(),
                        TBABlocks.BASKET_EBONY_ORANGE.get(),
                        TBABlocks.BASKET_EBONY_YELLOW.get(),
                        TBABlocks.BASKET_EBONY_LIME.get(),
                        TBABlocks.BASKET_EBONY_GREEN.get(),
                        TBABlocks.BASKET_EBONY_CYAN.get(),
                        TBABlocks.BASKET_EBONY_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_EBONY_BLUE.get(),
                        TBABlocks.BASKET_EBONY_PURPLE.get(),
                        TBABlocks.BASKET_EBONY_MAGENTA.get(),
                        TBABlocks.BASKET_EBONY_PINK.get(),
                        TBABlocks.BASKET_CHORUS_NEST_WHITE.get(),
                        TBABlocks.BASKET_CHORUS_NEST_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_CHORUS_NEST_GRAY.get(),
                        TBABlocks.BASKET_CHORUS_NEST_BLACK.get(),
                        TBABlocks.BASKET_CHORUS_NEST_BROWN.get(),
                        TBABlocks.BASKET_CHORUS_NEST_RED.get(),
                        TBABlocks.BASKET_CHORUS_NEST_ORANGE.get(),
                        TBABlocks.BASKET_CHORUS_NEST_YELLOW.get(),
                        TBABlocks.BASKET_CHORUS_NEST_LIME.get(),
                        TBABlocks.BASKET_CHORUS_NEST_GREEN.get(),
                        TBABlocks.BASKET_CHORUS_NEST_CYAN.get(),
                        TBABlocks.BASKET_CHORUS_NEST_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_CHORUS_NEST_BLUE.get(),
                        TBABlocks.BASKET_CHORUS_NEST_PURPLE.get(),
                        TBABlocks.BASKET_CHORUS_NEST_MAGENTA.get(),
                        TBABlocks.BASKET_CHORUS_NEST_PINK.get(),
                        TBABlocks.BASKET_BLOODSHROOM_WHITE.get(),
                        TBABlocks.BASKET_BLOODSHROOM_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_BLOODSHROOM_GRAY.get(),
                        TBABlocks.BASKET_BLOODSHROOM_BLACK.get(),
                        TBABlocks.BASKET_BLOODSHROOM_BROWN.get(),
                        TBABlocks.BASKET_BLOODSHROOM_RED.get(),
                        TBABlocks.BASKET_BLOODSHROOM_ORANGE.get(),
                        TBABlocks.BASKET_BLOODSHROOM_YELLOW.get(),
                        TBABlocks.BASKET_BLOODSHROOM_LIME.get(),
                        TBABlocks.BASKET_BLOODSHROOM_GREEN.get(),
                        TBABlocks.BASKET_BLOODSHROOM_CYAN.get(),
                        TBABlocks.BASKET_BLOODSHROOM_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_BLOODSHROOM_BLUE.get(),
                        TBABlocks.BASKET_BLOODSHROOM_PURPLE.get(),
                        TBABlocks.BASKET_BLOODSHROOM_MAGENTA.get(),
                        TBABlocks.BASKET_BLOODSHROOM_PINK.get(),
                        TBABlocks.BASKET_ENDERBARK_WHITE.get(),
                        TBABlocks.BASKET_ENDERBARK_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_ENDERBARK_GRAY.get(),
                        TBABlocks.BASKET_ENDERBARK_BLACK.get(),
                        TBABlocks.BASKET_ENDERBARK_BROWN.get(),
                        TBABlocks.BASKET_ENDERBARK_RED.get(),
                        TBABlocks.BASKET_ENDERBARK_ORANGE.get(),
                        TBABlocks.BASKET_ENDERBARK_YELLOW.get(),
                        TBABlocks.BASKET_ENDERBARK_LIME.get(),
                        TBABlocks.BASKET_ENDERBARK_GREEN.get(),
                        TBABlocks.BASKET_ENDERBARK_CYAN.get(),
                        TBABlocks.BASKET_ENDERBARK_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_ENDERBARK_BLUE.get(),
                        TBABlocks.BASKET_ENDERBARK_PURPLE.get(),
                        TBABlocks.BASKET_ENDERBARK_MAGENTA.get(),
                        TBABlocks.BASKET_ENDERBARK_PINK.get(),
                        TBABlocks.BASKET_GREENHEART_WHITE.get(),
                        TBABlocks.BASKET_GREENHEART_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_GREENHEART_GRAY.get(),
                        TBABlocks.BASKET_GREENHEART_BLACK.get(),
                        TBABlocks.BASKET_GREENHEART_BROWN.get(),
                        TBABlocks.BASKET_GREENHEART_RED.get(),
                        TBABlocks.BASKET_GREENHEART_ORANGE.get(),
                        TBABlocks.BASKET_GREENHEART_YELLOW.get(),
                        TBABlocks.BASKET_GREENHEART_LIME.get(),
                        TBABlocks.BASKET_GREENHEART_GREEN.get(),
                        TBABlocks.BASKET_GREENHEART_CYAN.get(),
                        TBABlocks.BASKET_GREENHEART_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_GREENHEART_BLUE.get(),
                        TBABlocks.BASKET_GREENHEART_PURPLE.get(),
                        TBABlocks.BASKET_GREENHEART_MAGENTA.get(),
                        TBABlocks.BASKET_GREENHEART_PINK.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_WHITE.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_LIGHT_GRAY.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_GRAY.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_BLACK.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_BROWN.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_RED.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_ORANGE.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_YELLOW.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_LIME.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_GREEN.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_CYAN.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_LIGHT_BLUE.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_BLUE.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_PURPLE.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_MAGENTA.get(),
                        TBABlocks.BASKET_TINKER_SKYROOT_PINK.get()
                );
        tag(TBATags.Blocks.SERENE_SEASONS_SUMMER_CROPS)
                .add(TBABlocks.DILL_BUSH.get())
                .add(TBABlocks.CUCUMBER_BUSH.get())
                .add(TBABlocks.CLOVE_BUSH.get());
        tag(TBATags.Blocks.TBA_MINING_PORTAL_FRAME_BLOCKS)
                .add(Blocks.ANDESITE);
        tag(TBATags.Blocks.PLATES)
                .add(TBABlocks.PLATE_PURPLE.get())
                .add(TBABlocks.PLATE_PINK.get())
                .add(TBABlocks.PLATE_ORANGE.get())
                .add(TBABlocks.PLATE_MAGENTA.get())
                .add(TBABlocks.PLATE_LIME.get())
                .add(TBABlocks.PLATE_LIGHT_GRAY.get())
                .add(TBABlocks.PLATE_LIGHT_BLUE.get())
                .add(TBABlocks.PLATE_GREEN.get())
                .add(TBABlocks.PLATE_GRAY.get())
                .add(TBABlocks.PLATE_CYAN.get())
                .add(TBABlocks.PLATE_BROWN.get())
                .add(TBABlocks.PLATE_BLUE.get())
                .add(TBABlocks.PLATE_BLACK.get());
        tag(TBATags.Blocks.DESK_CABINETS)
                .add(TBABlocks.SCHOOL_DESK_CABINET_FIR.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_REDWOOD.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_CHERRY.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_MAHOGANY.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_JACARANDA.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_PALM.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_WILLOW.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_DEAD.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_MAGIC.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_UMBRAN.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_HELLBARK.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_COCONUT.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_WALNUT.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_AZALEA.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_FLOWERING_AZALEA.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_GOLDEN_OAK.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_AETHER_SKYROOT.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_PREAM.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_EBONY.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_CHORUS_NEST.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_BLOODSHROOM.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_ENDERBARK.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_GREENHEART.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_TINKER_SKYROOT.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_WARPED.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_CRIMSON.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_MANGROVE.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_OAK.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_BIRCH.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_SPRUCE.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_DARK_OAK.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_JUNGLE.get())
                .add(TBABlocks.SCHOOL_DESK_CABINET_ACACIA.get());
        tag(TBATags.Blocks.CHAIRS)
                .add(TBABlocks.DESK_CHAIR_FIR.get())
                .add(TBABlocks.DESK_CHAIR_REDWOOD.get())
                .add(TBABlocks.DESK_CHAIR_CHERRY.get())
                .add(TBABlocks.DESK_CHAIR_MAHOGANY.get())
                .add(TBABlocks.DESK_CHAIR_JACARANDA.get())
                .add(TBABlocks.DESK_CHAIR_PALM.get())
                .add(TBABlocks.DESK_CHAIR_WILLOW.get())
                .add(TBABlocks.DESK_CHAIR_DEAD.get())
                .add(TBABlocks.DESK_CHAIR_MAGIC.get())
                .add(TBABlocks.DESK_CHAIR_UMBRAN.get())
                .add(TBABlocks.DESK_CHAIR_HELLBARK.get())
                .add(TBABlocks.DESK_CHAIR_COCONUT.get())
                .add(TBABlocks.DESK_CHAIR_WALNUT.get())
                .add(TBABlocks.DESK_CHAIR_AZALEA.get())
                .add(TBABlocks.DESK_CHAIR_FLOWERING_AZALEA.get())
                .add(TBABlocks.DESK_CHAIR_GOLDEN_OAK.get())
                .add(TBABlocks.DESK_CHAIR_AETHER_SKYROOT.get())
                .add(TBABlocks.DESK_CHAIR_PREAM.get())
                .add(TBABlocks.DESK_CHAIR_EBONY.get())
                .add(TBABlocks.DESK_CHAIR_CHORUS_NEST.get())
                .add(TBABlocks.DESK_CHAIR_BLOODSHROOM.get())
                .add(TBABlocks.DESK_CHAIR_ENDERBARK.get())
                .add(TBABlocks.DESK_CHAIR_GREENHEART.get())
                .add(TBABlocks.DESK_CHAIR_TINKER_SKYROOT.get())
                .add(TBABlocks.DESK_CHAIR_WARPED.get())
                .add(TBABlocks.DESK_CHAIR_CRIMSON.get())
                .add(TBABlocks.DESK_CHAIR_MANGROVE.get())
                .add(TBABlocks.DESK_CHAIR_OAK.get())
                .add(TBABlocks.DESK_CHAIR_BIRCH.get())
                .add(TBABlocks.DESK_CHAIR_SPRUCE.get())
                .add(TBABlocks.DESK_CHAIR_DARK_OAK.get())
                .add(TBABlocks.DESK_CHAIR_JUNGLE.get())
                .add(TBABlocks.DESK_CHAIR_ACACIA.get());
        tag(TBATags.Blocks.BOOKCASES)
                .add(TBABlocks.BOOKCASE_FIR.get())
                .add(TBABlocks.BOOKCASE_REDWOOD.get())
                .add(TBABlocks.BOOKCASE_CHERRY.get())
                .add(TBABlocks.BOOKCASE_MAHOGANY.get())
                .add(TBABlocks.BOOKCASE_JACARANDA.get())
                .add(TBABlocks.BOOKCASE_PALM.get())
                .add(TBABlocks.BOOKCASE_WILLOW.get())
                .add(TBABlocks.BOOKCASE_DEAD.get())
                .add(TBABlocks.BOOKCASE_MAGIC.get())
                .add(TBABlocks.BOOKCASE_UMBRAN.get())
                .add(TBABlocks.BOOKCASE_HELLBARK.get())
                .add(TBABlocks.BOOKCASE_COCONUT.get())
                .add(TBABlocks.BOOKCASE_WALNUT.get())
                .add(TBABlocks.BOOKCASE_AZALEA.get())
                .add(TBABlocks.BOOKCASE_FLOWERING_AZALEA.get())
                .add(TBABlocks.BOOKCASE_GOLDEN_OAK.get())
                .add(TBABlocks.BOOKCASE_AETHER_SKYROOT.get())
                .add(TBABlocks.BOOKCASE_PREAM.get())
                .add(TBABlocks.BOOKCASE_EBONY.get())
                .add(TBABlocks.BOOKCASE_CHORUS_NEST.get())
                .add(TBABlocks.BOOKCASE_BLOODSHROOM.get())
                .add(TBABlocks.BOOKCASE_ENDERBARK.get())
                .add(TBABlocks.BOOKCASE_GREENHEART.get())
                .add(TBABlocks.BOOKCASE_TINKER_SKYROOT.get())
                .add(TBABlocks.BOOKCASE_WARPED.get())
                .add(TBABlocks.BOOKCASE_CRIMSON.get())
                .add(TBABlocks.BOOKCASE_MANGROVE.get())
                .add(TBABlocks.BOOKCASE_OAK.get())
                .add(TBABlocks.BOOKCASE_BIRCH.get())
                .add(TBABlocks.BOOKCASE_SPRUCE.get())
                .add(TBABlocks.BOOKCASE_DARK_OAK.get())
                .add(TBABlocks.BOOKCASE_JUNGLE.get())
                .add(TBABlocks.BOOKCASE_ACACIA.get());
        tag(TBATags.Blocks.LOCKERS)
                .add(TBABlocks.LOCKER_FIR.get())
                .add(TBABlocks.LOCKER_REDWOOD.get())
                .add(TBABlocks.LOCKER_CHERRY.get())
                .add(TBABlocks.LOCKER_MAHOGANY.get())
                .add(TBABlocks.LOCKER_JACARANDA.get())
                .add(TBABlocks.LOCKER_PALM.get())
                .add(TBABlocks.LOCKER_WILLOW.get())
                .add(TBABlocks.LOCKER_DEAD.get())
                .add(TBABlocks.LOCKER_MAGIC.get())
                .add(TBABlocks.LOCKER_UMBRAN.get())
                .add(TBABlocks.LOCKER_HELLBARK.get())
                .add(TBABlocks.LOCKER_COCONUT.get())
                .add(TBABlocks.LOCKER_WALNUT.get())
                .add(TBABlocks.LOCKER_AZALEA.get())
                .add(TBABlocks.LOCKER_FLOWERING_AZALEA.get())
                .add(TBABlocks.LOCKER_GOLDEN_OAK.get())
                .add(TBABlocks.LOCKER_AETHER_SKYROOT.get())
                .add(TBABlocks.LOCKER_PREAM.get())
                .add(TBABlocks.LOCKER_EBONY.get())
                .add(TBABlocks.LOCKER_CHORUS_NEST.get())
                .add(TBABlocks.LOCKER_BLOODSHROOM.get())
                .add(TBABlocks.LOCKER_ENDERBARK.get())
                .add(TBABlocks.LOCKER_GREENHEART.get())
                .add(TBABlocks.LOCKER_TINKER_SKYROOT.get())
                .add(TBABlocks.LOCKER_WARPED.get())
                .add(TBABlocks.LOCKER_CRIMSON.get())
                .add(TBABlocks.LOCKER_MANGROVE.get())
                .add(TBABlocks.LOCKER_OAK.get())
                .add(TBABlocks.LOCKER_BIRCH.get())
                .add(TBABlocks.LOCKER_SPRUCE.get())
                .add(TBABlocks.LOCKER_DARK_OAK.get())
                .add(TBABlocks.LOCKER_JUNGLE.get())
                .add(TBABlocks.LOCKER_ACACIA.get());
        tag(TBATags.Blocks.BENCHES)
                .add(TBABlocks.PARK_BENCH_FIR.get())
                .add(TBABlocks.PARK_BENCH_REDWOOD.get())
                .add(TBABlocks.PARK_BENCH_CHERRY.get())
                .add(TBABlocks.PARK_BENCH_MAHOGANY.get())
                .add(TBABlocks.PARK_BENCH_JACARANDA.get())
                .add(TBABlocks.PARK_BENCH_PALM.get())
                .add(TBABlocks.PARK_BENCH_WILLOW.get())
                .add(TBABlocks.PARK_BENCH_DEAD.get())
                .add(TBABlocks.PARK_BENCH_MAGIC.get())
                .add(TBABlocks.PARK_BENCH_UMBRAN.get())
                .add(TBABlocks.PARK_BENCH_HELLBARK.get())
                .add(TBABlocks.PARK_BENCH_COCONUT.get())
                .add(TBABlocks.PARK_BENCH_WALNUT.get())
                .add(TBABlocks.PARK_BENCH_AZALEA.get())
                .add(TBABlocks.PARK_BENCH_FLOWERING_AZALEA.get())
                .add(TBABlocks.PARK_BENCH_GOLDEN_OAK.get())
                .add(TBABlocks.PARK_BENCH_AETHER_SKYROOT.get())
                .add(TBABlocks.PARK_BENCH_PREAM.get())
                .add(TBABlocks.PARK_BENCH_EBONY.get())
                .add(TBABlocks.PARK_BENCH_CHORUS_NEST.get())
                .add(TBABlocks.PARK_BENCH_BLOODSHROOM.get())
                .add(TBABlocks.PARK_BENCH_ENDERBARK.get())
                .add(TBABlocks.PARK_BENCH_GREENHEART.get())
                .add(TBABlocks.PARK_BENCH_TINKER_SKYROOT.get())
                .add(TBABlocks.PARK_BENCH_WARPED.get())
                .add(TBABlocks.PARK_BENCH_CRIMSON.get())
                .add(TBABlocks.PARK_BENCH_MANGROVE.get())
                .add(TBABlocks.PARK_BENCH_OAK.get())
                .add(TBABlocks.PARK_BENCH_BIRCH.get())
                .add(TBABlocks.PARK_BENCH_SPRUCE.get())
                .add(TBABlocks.PARK_BENCH_DARK_OAK.get())
                .add(TBABlocks.PARK_BENCH_JUNGLE.get())
                .add(TBABlocks.PARK_BENCH_ACACIA.get());
        tag(TBATags.Blocks.TABLES)
                .add(TBABlocks.TABLE_FIR.get())
                .add(TBABlocks.TABLE_REDWOOD.get())
                .add(TBABlocks.TABLE_CHERRY.get())
                .add(TBABlocks.TABLE_MAHOGANY.get())
                .add(TBABlocks.TABLE_JACARANDA.get())
                .add(TBABlocks.TABLE_PALM.get())
                .add(TBABlocks.TABLE_WILLOW.get())
                .add(TBABlocks.TABLE_DEAD.get())
                .add(TBABlocks.TABLE_MAGIC.get())
                .add(TBABlocks.TABLE_UMBRAN.get())
                .add(TBABlocks.TABLE_HELLBARK.get())
                .add(TBABlocks.TABLE_COCONUT.get())
                .add(TBABlocks.TABLE_WALNUT.get())
                .add(TBABlocks.TABLE_AZALEA.get())
                .add(TBABlocks.TABLE_FLOWERING_AZALEA.get())
                .add(TBABlocks.TABLE_GOLDEN_OAK.get())
                .add(TBABlocks.TABLE_AETHER_SKYROOT.get())
                .add(TBABlocks.TABLE_PREAM.get())
                .add(TBABlocks.TABLE_EBONY.get())
                .add(TBABlocks.TABLE_CHORUS_NEST.get())
                .add(TBABlocks.TABLE_BLOODSHROOM.get())
                .add(TBABlocks.TABLE_ENDERBARK.get())
                .add(TBABlocks.TABLE_GREENHEART.get())
                .add(TBABlocks.TABLE_TINKER_SKYROOT.get())
                .add(TBABlocks.TABLE_WARPED.get())
                .add(TBABlocks.TABLE_CRIMSON.get())
                .add(TBABlocks.TABLE_MANGROVE.get())
                .add(TBABlocks.TABLE_OAK.get())
                .add(TBABlocks.TABLE_BIRCH.get())
                .add(TBABlocks.TABLE_SPRUCE.get())
                .add(TBABlocks.TABLE_DARK_OAK.get())
                .add(TBABlocks.TABLE_JUNGLE.get())
                .add(TBABlocks.TABLE_ACACIA.get());
        tag(TBATags.Blocks.DESKS)
                .add(TBABlocks.SCHOOL_DESK_FIR.get())
                .add(TBABlocks.SCHOOL_DESK_REDWOOD.get())
                .add(TBABlocks.SCHOOL_DESK_CHERRY.get())
                .add(TBABlocks.SCHOOL_DESK_MAHOGANY.get())
                .add(TBABlocks.SCHOOL_DESK_JACARANDA.get())
                .add(TBABlocks.SCHOOL_DESK_PALM.get())
                .add(TBABlocks.SCHOOL_DESK_WILLOW.get())
                .add(TBABlocks.SCHOOL_DESK_DEAD.get())
                .add(TBABlocks.SCHOOL_DESK_MAGIC.get())
                .add(TBABlocks.SCHOOL_DESK_UMBRAN.get())
                .add(TBABlocks.SCHOOL_DESK_HELLBARK.get())
                .add(TBABlocks.SCHOOL_DESK_COCONUT.get())
                .add(TBABlocks.SCHOOL_DESK_WALNUT.get())
                .add(TBABlocks.SCHOOL_DESK_AZALEA.get())
                .add(TBABlocks.SCHOOL_DESK_FLOWERING_AZALEA.get())
                .add(TBABlocks.SCHOOL_DESK_GOLDEN_OAK.get())
                .add(TBABlocks.SCHOOL_DESK_AETHER_SKYROOT.get())
                .add(TBABlocks.SCHOOL_DESK_PREAM.get())
                .add(TBABlocks.SCHOOL_DESK_EBONY.get())
                .add(TBABlocks.SCHOOL_DESK_CHORUS_NEST.get())
                .add(TBABlocks.SCHOOL_DESK_BLOODSHROOM.get())
                .add(TBABlocks.SCHOOL_DESK_ENDERBARK.get())
                .add(TBABlocks.SCHOOL_DESK_GREENHEART.get())
                .add(TBABlocks.SCHOOL_DESK_TINKER_SKYROOT.get())
                .add(TBABlocks.SCHOOL_DESK_WARPED.get())
                .add(TBABlocks.SCHOOL_DESK_CRIMSON.get())
                .add(TBABlocks.SCHOOL_DESK_MANGROVE.get())
                .add(TBABlocks.SCHOOL_DESK_OAK.get())
                .add(TBABlocks.SCHOOL_DESK_BIRCH.get())
                .add(TBABlocks.SCHOOL_DESK_SPRUCE.get())
                .add(TBABlocks.SCHOOL_DESK_DARK_OAK.get())
                .add(TBABlocks.SCHOOL_DESK_JUNGLE.get())
                .add(TBABlocks.SCHOOL_DESK_ACACIA.get());
        tag(TBATags.Blocks.DROPS_FOUR_LEAF_CLOVER)
                .addOptional(Objects.requireNonNull(ResourceLocation.tryParse("biomesoplenty:clover")))
                .addOptional(Objects.requireNonNull(ResourceLocation.tryParse("biomesoplenty:huge_clover_petal")))
                .addOptional(PhantasmModBlocks.ENDER_CLOVER.getId())
                .add(Blocks.GRASS)
                .add(Blocks.TALL_GRASS);
        tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(Blocks.REINFORCED_DEEPSLATE);
        tag(TBATags.Blocks.NEEDS_NETHERITE_TOOL)
                .add(Blocks.REINFORCED_DEEPSLATE);
        tag(TBATags.Blocks.FD_HEAT_CONDUCTORS)
                .addOptional(Objects.requireNonNull(ResourceLocation.tryParse("create:chute")))
                .addOptional(Objects.requireNonNull(ResourceLocation.tryParse("goldenhopper:golden_hopper")));
        tag(TBATags.Blocks.FD_HEAT_SOURCES)
                .add(Blocks.MAGMA_BLOCK)
                .add(Blocks.LAVA_CAULDRON)
                .addTag(TBATags.Blocks.FD_TRAY_HEAT_SOURCES)
                .addOptional(MoaDecorCookeryModItems.ESTUFA.getId())
                .addOptional(MoaDecorCookeryModItems.ESTUFAABIERTA.getId())
                .addOptional(MoaDecorCookeryModItems.ESTUFAPAY.getId())
                .addOptional(Objects.requireNonNull(ResourceLocation.tryParse("nfm:oven_light")))
                .addOptional(Objects.requireNonNull(ResourceLocation.tryParse("nfm:oven_dark")))
                .addOptional(Objects.requireNonNull(ResourceLocation.tryParse("handcrafted:oven")));
        tag(TBATags.Blocks.FD_TRAY_HEAT_SOURCES)
                .addOptional(Objects.requireNonNull(ResourceLocation.tryParse("exlinefurniture:oven")));
        tag(TBATags.Blocks.FR_HEAT_CONDUCTORS).addTag(TBATags.Blocks.FD_HEAT_CONDUCTORS);
        tag(TBATags.Blocks.FR_HEAT_SOURCES).addTag(TBATags.Blocks.FD_HEAT_SOURCES);
        tag(TBATags.Blocks.FR_TRAY_HEAT_SOURCES).addTag(TBATags.Blocks.FD_TRAY_HEAT_SOURCES);
        tag(TBATags.Blocks.CARPETS)
                .add(Blocks.WHITE_CARPET)
                .add(Blocks.LIGHT_GRAY_CARPET)
                .add(Blocks.GRAY_CARPET)
                .add(Blocks.BLACK_CARPET)
                .add(Blocks.BROWN_CARPET)
                .add(Blocks.RED_CARPET)
                .add(Blocks.ORANGE_CARPET)
                .add(Blocks.YELLOW_CARPET)
                .add(Blocks.GREEN_CARPET)
                .add(Blocks.LIME_CARPET)
                .add(Blocks.CYAN_CARPET)
                .add(Blocks.BLUE_CARPET)
                .add(Blocks.LIGHT_BLUE_CARPET)
                .add(Blocks.PINK_CARPET)
                .add(Blocks.MAGENTA_CARPET)
                .add(Blocks.PURPLE_CARPET);
        tag(TBATags.Blocks.SAND)
                .addOptional(BOPBlocks.WHITE_SAND.getId())
                .addOptional(BOPBlocks.ROOTED_SAND.getId())
                .addOptional(BOPBlocks.ORANGE_SAND.getId())
                .addOptional(BOPBlocks.BLACK_SAND.getId())
                .add(Blocks.SAND)
                .add(Blocks.RED_SAND);
        tag(TBATags.Blocks.GLASS)
                .addOptional(UnusualendModItems.CHISELED_GLASS.getId())
                .addOptional(PhantasmModItems.CRYSTAL_FRAMED_GLASS.getId())
                .addOptional(PhantasmModItems.VOID_CRYSTAL_FRAMED_GLASS.getId());
        tag(TBATags.Blocks.GINGERBREADS)
                .addOptional(Objects.requireNonNull(ResourceLocation.tryParse("snowyspirit:gingerbread_frosted")))
                .addOptional(Objects.requireNonNull(ResourceLocation.tryParse("snowyspirit:gingerbread")))
                .addOptional(FestiveDelightModBlocks.GINGERBREAD_BLOCK.getId())
                .addOptional(FestiveDelightModBlocks.GINGERBREAD_BLOCK_CREEPER.getId())
                .addOptional(FestiveDelightModBlocks.GINGERBREAD_BLOCK_DIAMOND.getId())
                .addOptional(FestiveDelightModBlocks.GINGERBREAD_BLOCK_DECORATIONS.getId())
                .addOptional(FestiveDelightModBlocks.GINGERBREAD_BLOCK_SNOW.getId())
                .addOptional(FestiveDelightModBlocks.GINGERBREAD_PILLAR.getId())
                .addOptional(FestiveDelightModBlocks.POLISHED_GINGERBREAD_BLOCK.getId());
    }
}