package com.github.warrentode.turtleblockacademy.datagen.loot.tables;

import biomesoplenty.api.block.BOPBlocks;
import com.github.warrentode.turtleblockacademy.loot.tables.DimDungeonLootTables;
import com.github.warrentode.turtleblockacademy.loot.tables.KitchenLootTables;
import com.github.warrentode.turtleblockacademy.loot.tables.PackBuiltInLootTables;
import com.github.warrentode.turtleblockacademy.util.PackTags;
import net.mcreator.festivedelight.init.FestiveDelightModBlocks;
import net.mcreator.phantasm.init.PhantasmModBlocks;
import net.mcreator.unusualend.init.UnusualendModBlocks;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.entries.LootTableReference;
import net.minecraft.world.level.storage.loot.entries.TagEntry;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;
import org.jetbrains.annotations.NotNull;
import sereneseasons.api.SSBlocks;
import vectorwing.farmersdelight.common.registry.ModItems;

import java.util.function.BiConsumer;
import java.util.function.Consumer;

import static com.aetherteam.aether.block.AetherBlocks.*;
import static com.github.warrentode.turtleblockacademy.datagen.loot.ModLootProviders.*;
import static com.mrcrayfish.goldenhopper.init.ModBlocks.GOLDEN_HOPPER;
import static com.refinedmods.refinedstorage.RSItems.*;
import static decor.delight.init.DecorationDelightModItems.*;
import static net.mcreator.phantasm.init.PhantasmModItems.*;
import static net.mcreator.unusualend.init.UnusualendModItems.*;
import static net.mehvahdjukaar.snowyspirit.reg.ModRegistry.*;
import static net.mehvahdjukaar.supplementaries.reg.ModRegistry.*;
import static samebutdifferent.ecologics.registry.ModBlocks.*;

public class DimDungeonLootTablesGen implements Consumer<BiConsumer<ResourceLocation, LootTable.Builder>> {
    @Override
    public void accept(@NotNull BiConsumer<ResourceLocation, LootTable.Builder> consumer) {
        consumer.accept(DimDungeonLootTables.KIT_RANDOM, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(ConstantValue.exactly(1))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_LOGS))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_WOOL))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_CONCRETE))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_GLASS))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_SAND))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_INGOTS))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_REDSTONE))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_TERRACOTTA))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_GLAZED_TERRACOTTA))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_STONE))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_SANDSTONE))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_BLACKSTONE)
                                .when(IN_NETHER.or(IN_DUNGEON)))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_DEEPSLATE))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_PRISMARINE))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_END_STONES)
                                .when(IN_END.or(IN_DUNGEON)))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_PURPUR_STONES)
                                .when(IN_END.or(IN_DUNGEON)))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_CREATURE_STONES)
                                .when(IN_END.or(IN_DUNGEON)))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_OBSIDIAN))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_CRYSTAL)
                                .when(IN_END.or(IN_DUNGEON)))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_BRICK_SET))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_QUARTZ)
                                .when(IN_NETHER.or(IN_DUNGEON)))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_MISC))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_DECOR))
                        .add(LootTableReference.lootTableReference(DimDungeonLootTables.KIT_CHRISTMAS_BLOCKS)
                                .when(CHRISTMAS_EVENT))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_FOOD, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_food")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.VANILLA_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.CRABBERSDELIGHT_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.OCEANSDELIGHT_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.KAWAIIDISHES_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.FARMERSRESPITE_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.DRINKBEERREFILL_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.WILDBERRIES_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.FASTFOODDELIGHT_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.FESTIVEDELIGHT_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.DELIGHTFUL_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.FARMERSRESPITE_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.HAUNTEDHARVEST_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.SNOWYSPIRIT_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.SUPPLEMENTARIES_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.ENDSDELIGHT_EDIBLES).when(IN_END)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.PHANTASM_EDIBLES).when(IN_END)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.UNUSUALEND_EDIBLES).when(IN_END)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.ECOLOGICS_EDIBLES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.AETHER_EDIBLES).when(IN_AETHER)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootTableReference.lootTableReference(KitchenLootTables.NETHERSSDELIGHT_EDIBLES).when(IN_NETHER)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_CONCRETE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_concrete")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.BLACK_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.BLUE_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.BROWN_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CYAN_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.GREEN_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.GRAY_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIME_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.MAGENTA_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.ORANGE_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PINK_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PURPLE_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.RED_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIGHT_BLUE_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIGHT_GRAY_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.WHITE_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.YELLOW_CONCRETE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_GLASS, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_glass")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.TINTED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.BLACK_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.BLUE_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.BROWN_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CYAN_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.GREEN_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.GRAY_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIME_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.MAGENTA_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.ORANGE_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PINK_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PURPLE_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.RED_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIGHT_BLUE_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIGHT_GRAY_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.WHITE_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.YELLOW_STAINED_GLASS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(UnusualendModBlocks.CHISELED_GLASS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(PhantasmModBlocks.CRYSTAL_FRAMED_GLASS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(PhantasmModBlocks.VOID_CRYSTAL_FRAMED_GLASS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(TagEntry.expandTag(PackTags.Items.GLASS_INFUSED)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(TagEntry.expandTag(PackTags.Items.GLASS_REINFORCED)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(TagEntry.expandTag(PackTags.Items.GLASS_GLOWING)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(TagEntry.expandTag(PackTags.Items.GLASS_SHIFTING)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(QUICKSOIL_GLASS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_REDSTONE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_redstone")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Items.REDSTONE).setWeight(20)
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                        .add(LootItem.lootTableItem(Items.PISTON)
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                        .add(LootItem.lootTableItem(Items.STICKY_PISTON)
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                        .add(LootItem.lootTableItem(Items.REDSTONE_TORCH).setWeight(2)
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                        .add(LootItem.lootTableItem(Items.HOPPER).setWeight(4)
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                        .add(LootItem.lootTableItem(Items.REPEATER).setWeight(2)
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COMPARATOR)
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                        .add(LootItem.lootTableItem(Items.DAYLIGHT_DETECTOR)
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                        .add(LootItem.lootTableItem(Items.REDSTONE_LAMP)
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                        .add(LootItem.lootTableItem(Items.OBSERVER)
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                        .add(LootItem.lootTableItem(Items.STICKY_PISTON)
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                        .add(LootItem.lootTableItem(GOLDEN_HOPPER.get())
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                        .add(LootItem.lootTableItem(SSBlocks.SEASON_SENSOR.get())
                                .apply(SetItemCountFunction.setCount(ConstantValue.exactly(1))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_WOOL, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_wool")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.BLACK_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.BLUE_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.BROWN_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CYAN_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.GREEN_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.GRAY_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIME_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.MAGENTA_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.ORANGE_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PINK_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PURPLE_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.RED_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIGHT_BLUE_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIGHT_GRAY_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.WHITE_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.YELLOW_WOOL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_INGOTS, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_ingots")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Items.COPPER_INGOT).setWeight(30)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Items.IRON_INGOT).setWeight(20)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Items.GOLD_INGOT).setWeight(15)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(QUARTZ_ENRICHED_IRON.get()).setWeight(5).when(IN_NETHER)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))))
                        .add(LootItem.lootTableItem(Items.NETHERITE_INGOT).setWeight(1).when(IN_NETHER)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))))
                        .add(TagEntry.expandTag(PackTags.Items.ENDONIAN_INGOT).setWeight(10).when(IN_END)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1, 5))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_TERRACOTTA, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_terracotta")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.BLACK_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.BLUE_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.BROWN_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CYAN_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.GREEN_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.GRAY_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIME_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.MAGENTA_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.ORANGE_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PINK_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PURPLE_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.RED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIGHT_BLUE_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIGHT_GRAY_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.WHITE_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.YELLOW_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_GLAZED_TERRACOTTA, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_terracotta")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.BLACK_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.BLUE_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.BROWN_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CYAN_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.GREEN_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.GRAY_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIME_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.MAGENTA_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.ORANGE_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PINK_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PURPLE_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.RED_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.WHITE_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.YELLOW_GLAZED_TERRACOTTA)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_STONE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_stone")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.STONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.STONE_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.MOSSY_STONE_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CRACKED_STONE_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CHISELED_STONE_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.SMOOTH_STONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.COBBLESTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.MOSSY_COBBLESTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(STONE_LAMP.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(STONE_TILES.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(TagEntry.expandTag(PackTags.Items.STONE_TILE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CARVED_STONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.ANDESITE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.POLISHED_ANDESITE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(ANDESITE_TILES.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_SANDSTONE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_sandstone")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.SANDSTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CHISELED_SANDSTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CUT_SANDSTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.SMOOTH_SANDSTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.RED_SANDSTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CHISELED_RED_SANDSTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CUT_RED_SANDSTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.SMOOTH_RED_SANDSTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.WHITE_SANDSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.SMOOTH_WHITE_SANDSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.CUT_WHITE_SANDSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.CHISELED_WHITE_SANDSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.ORANGE_SANDSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.SMOOTH_ORANGE_SANDSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.CUT_ORANGE_SANDSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.CHISELED_ORANGE_SANDSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.BLACK_SANDSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.SMOOTH_BLACK_SANDSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.CUT_BLACK_SANDSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.CHISELED_BLACK_SANDSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_MISC_STONE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_misc_stone")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.GRANITE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.POLISHED_GRANITE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(GRANITE_TILES.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.DIORITE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.POLISHED_DIORITE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(DIORITE_TILES.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))

                        .add(LootItem.lootTableItem(SENTRY_STONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(ANGELIC_STONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(LIGHT_ANGELIC_STONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(PILLAR.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(PILLAR_TOP.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(HELLFIRE_STONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(LIGHT_HELLFIRE_STONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(HOLYSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(MOSSY_HOLYSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(AEROGEL.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BLUE_AERCLOUD.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(COLD_AERCLOUD.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(GOLDEN_AERCLOUD.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))

                        .add(LootItem.lootTableItem(Blocks.DRIPSTONE_BLOCK)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CALCITE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.TUFF)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.BRIMSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))

                        .add(LootItem.lootTableItem(Blocks.BASALT)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.SMOOTH_BASALT)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.POLISHED_BASALT)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))

                        .add(LootItem.lootTableItem(Blocks.OCHRE_FROGLIGHT)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PEARLESCENT_FROGLIGHT)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.VERDANT_FROGLIGHT)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_BLACKSTONE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_blackstone")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.BLACKSTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.GILDED_BLACKSTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.POLISHED_BLACKSTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CHISELED_POLISHED_BLACKSTONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.POLISHED_BLACKSTONE_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BLACKSTONE_LAMP.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(TagEntry.expandTag(PackTags.Items.BLACKSTONE_TILE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_DEEPSLATE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_deepslate")
                        .add(LootItem.lootTableItem(Blocks.DEEPSLATE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.COBBLED_DEEPSLATE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.POLISHED_DEEPSLATE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.DEEPSLATE_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CRACKED_DEEPSLATE_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.DEEPSLATE_TILES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CRACKED_DEEPSLATE_TILES)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CHISELED_DEEPSLATE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.REINFORCED_DEEPSLATE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(DEEPSLATE_LAMP.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_PRISMARINE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_sea_stones")
                        .add(LootItem.lootTableItem(Blocks.PRISMARINE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PRISMARINE_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.DARK_PRISMARINE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.SEA_LANTERN)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_END_STONES, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_end_stones")
                        .add(LootItem.lootTableItem(Blocks.END_STONE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.END_STONE_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(FADING_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(INFUSED_END_STONE_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(ENDSTONE_TILES.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CHISELED_ENDSTONE_BUILDER.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CHISELED_ENDSTONE_US.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CHISELED_ENDSTONE_DRAGON.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CHISELED_ENDSTONE_SCARED.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CHISELED_ENDSTONE_WORK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CHISELED_ENDSTONE_FRIENDSHIP.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(END_STONE_LAMP.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_PURPUR_STONES, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_purpur_stones")
                        .add(LootItem.lootTableItem(RAW_PURPUR.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(RAW_PURPUR_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CRACKED_RAW_PURPUR_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CHISELED_RAW_PURPUR.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(RAW_PURPUR_PILLAR.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(RAW_PURPUR_TILES.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(RAW_PURPUR_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(POLISHED_PURPUR.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(POLISHED_PURPUR_TILES.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(POLISHED_PURPUR_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CHISELED_POLISHED_PURPUR_TILES.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(POLISHED_PURPUR_TILES_LANTERN.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(PURPUR_LAMP.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_CREATURE_STONES, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_creature_stones")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(BOLOK_SCALE_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(POLISHED_GNEISS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(GNEISS_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))

                        .add(LootItem.lootTableItem(ENDERMITE_MOULT_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(ENDERMITE_MOULT_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))

                        .add(LootItem.lootTableItem(GLOOPSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(POLISHED_GLOOPSTONE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(GLOOPSTONE_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))

                        .add(LootItem.lootTableItem(SHINY_CRYSTAL_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(SHINY_CRYSTAL_TILES.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(SHINY_CRYSTAL_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_OBSIDIAN, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_obsidian")
                        .add(LootItem.lootTableItem(Blocks.OBSIDIAN)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CRYING_OBSIDIAN)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(SMOOTH_OBSIDIAN.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(SMOOTH_OBSIDIAN_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(SMOOTH_OBSIDIAN_PILLAR.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CHISELED_SMOOTH_OBSIDIAN.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(SMOOTH_OBSIDIAN_LAMP.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_CRYSTAL, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_crystal")
                        .add(LootItem.lootTableItem(CRYSTAL_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CRYSTILES.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CRYSTILES_PILLAR.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(VOID_CRYSTAL_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(VOID_CRYSTILES.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(VOID_CRYSTILES_PILLAR.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(STELLIUM_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(STELLIUM_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_BRICK_SET, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_brick_set")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(TagEntry.expandTag(PackTags.Items.LAPIS_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(TagEntry.expandTag(PackTags.Items.ASH_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.MUD_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.NETHER_BRICKS).when(IN_NETHER.or(IN_DUNGEON))
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.RED_NETHER_BRICKS).when(IN_NETHER.or(IN_DUNGEON))
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.SHROOMLIGHT).when(IN_NETHER.or(IN_DUNGEON))
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(HOLYSTONE_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_QUARTZ, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_quartz")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.SMOOTH_QUARTZ)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.CHISELED_QUARTZ_BLOCK)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.QUARTZ_BLOCK)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.QUARTZ_BRICKS)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.QUARTZ_PILLAR)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))

                        .add(LootItem.lootTableItem(QUARTZ_AND_BLACKSTONE_TILES.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CHECKER_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_CHRISTMAS_BLOCKS, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_christmas_blocks")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(FestiveDelightModBlocks.GINGERBREAD_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(FestiveDelightModBlocks.GINGERBREAD_BLOCK_CREEPER.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(FestiveDelightModBlocks.GINGERBREAD_BLOCK_DIAMOND.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(FestiveDelightModBlocks.GINGERBREAD_BLOCK_DECORATIONS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(FestiveDelightModBlocks.GINGERBREAD_BLOCK_SNOW.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(FestiveDelightModBlocks.GINGERBREAD_PILLAR.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(FestiveDelightModBlocks.POLISHED_GINGERBREAD_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(GINGERBREAD_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(GINGERBREAD_FROSTED_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(CANDY_CANE_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_WINTER_BLOCKS, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_winter_blocks")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(ICE_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(SNOW_BRICKS.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.ICE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.PACKED_ICE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.BLUE_ICE)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(THIN_ICE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_LOGS, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_logs")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootTableReference.lootTableReference(PackBuiltInLootTables.LOG_SET))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_SAND, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_sand")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.SAND)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Blocks.RED_SAND)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.BLACK_SAND.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.ORANGE_SAND.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.ROOTED_SAND.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(BOPBlocks.WHITE_SAND.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_MISC, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_misc")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootItem.lootTableItem(Blocks.COAL_BLOCK)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(FLINT_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(FEATHER_BLOCK.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Items.IRON_INGOT)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(ModItems.ROPE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(ROPE.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Items.TORCH)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(Items.SLIME_BALL)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(SILICON.get()).when(IN_NETHER)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                        .add(LootItem.lootTableItem(PROCESSOR_BINDING.get())
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(5, 9))))
                )
        );
        consumer.accept(DimDungeonLootTables.KIT_DECOR, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .name("dimdungeons:kit_decor")
                        .setRolls(ConstantValue.exactly(27))
                        .add(LootTableReference.lootTableReference(PackBuiltInLootTables.HOLIDAY_DECO))
                        .add(LootTableReference.lootTableReference(PackBuiltInLootTables.PLUSHIES))
                        .add(LootTableReference.lootTableReference(PackBuiltInLootTables.BATH_DECO))
                        .add(LootTableReference.lootTableReference(PackBuiltInLootTables.SCIENCE_DECO).when(AUTUMN.or(WINTER)))
                        .add(LootTableReference.lootTableReference(PackBuiltInLootTables.ART_DECO).when(AUTUMN.or(WINTER)))
                        .add(LootTableReference.lootTableReference(PackBuiltInLootTables.COOKERY_DECO))
                        .add(LootTableReference.lootTableReference(PackBuiltInLootTables.GARDEN_DECO).when(SPRING.or(SUMMER)))
                        .add(LootTableReference.lootTableReference(PackBuiltInLootTables.MISC_DECO))
                )
        );
    }
}
