name: Pull Request & Master CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(java -XshowSettings:properties -version 2>&1 | grep 'java.home' | awk '{print \$3}')" >> $GITHUB_ENV

      - name: Check Gradle Wrapper Permissions
        run: ls -l gradlew

      - name: Make Gradle executable
        run: |
          cd https://github.com/warrentode/TurtleBlockAcademy
          chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew test --stacktrace

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to Maven Local
        run: ./gradlew publishToMavenLocal

      - name: Publish to JitPack
        run: ./gradlew publish
